### ISSUE TITLE
"Inbox" still set as default first tab even though removed

### ISSUE THREAD

**Issue by firefoxlover** [XilinJia/Podcini#10]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.2.2

### Where did you get the app from

Other

### Android version

GrapheneOS Android 14

### Device model

not important

### First occurred

update I guess

### Steps to reproduce

Go to settings, interface, "default first page"

It is still set as "inbox" even though afaik that was removed and replaced with "episodes"

### Expected behaviour

Show "episodes" here

### Current behaviour

Is set to "inbox" which does not exist

### Logs

None

**Comment by XilinJia** [comment]
OK, need to remove item Inbox in default page setting

**Comment by XilinJia** [comment]
fixed in 4.2.3
