### ISSUE TITLE
Articles feed can be Subscribed, but can't open normally/图文feed可以订阅，但无法正常打开

### ISSUE THREAD

**Issue by Clayblockunova** [XilinJia/Podcini#101]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.11.1

### Where did you get the app from

Other

### Android version

HarmonyOS 3.0.0 (custom rom)

### Device model

Huawei Mate 10 Pro

### First occurred

recently

### Steps to reproduce

1. Import non-podcast (articles) feed with RSS URL or OPML. / 使用RSS地址或OPML导入非播客(图文)feed。
2. Open and refresh the queue of the feed. / 打开并刷新feed内播放列表。

### Expected behaviour

Articles feed can be refreshed and opened normally. /图文feed可正常刷新并打开。

### Current behaviour

App exits after opening articles feed. / 打开图文feed会导致APP退出。

**Comment by XilinJia** [comment]
Thanks for the info.  Can you give me some examples?

**Comment by Clayblockunova** [comment]
Example as below.
案例如下。
![微信图片_20241017083508](https://github.com/user-attachments/assets/177453e5-2b80-471e-8711-d5d0f216a3c6)
MDN Blog (feed URL:https://developer.mozilla.org/en-US/blog/rss.xml) is articles feed.
图中MDN Blog(feed地址:https://developer.mozilla.org/en-US/blog/rss.xml)为图文feed。

**Comment by XilinJia** [comment]
I see, so this is a plain RSS without any media.

Here is what I did and things appear normal.

- from NavDrawer, select Add podcast
- at the top search bar, enter the http address, tap search
- tap Subscribe, then Open
- in the FeedEpisodes view, open any episode, there is some info
- tap the house icon in the header area, then you get more info
- if you want to see more, tap the house icon on the top bar, you get the full web view of the page.

Is that what you want?

**Comment by Clayblockunova** [comment]
Yes.
是的。

**Comment by Clayblockunova** [comment]
Updated to 6.11.4, fixed.
更新至6.11.4版，问题解决。

**Comment by XilinJia** [comment]
> Updated to 6.11.4, fixed.

6.11.4 doesn't have any change on this.  Earlier versions should behave the same, no?
