### ISSUE TITLE
re-enable manual sorting of queues

### ISSUE THREAD

**Issue by ehula** [XilinJia/Podcini#102]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/podcini/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/Podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

v6.11.6

### Where did you get the app from

Other

### Problem you may be having, or feature you want

I'm not sure if this was a conscious decision, or the result of making other changes. We used to be able to manually sort queues. Somehow that functionality is no longer there.

I would like to have that feature back.

My use case:

I have multiple queues. One is "news". The episodes are from multiple different podcasts, and are stand alone. i.e. You don't need to listen to every episode in order. I have the queue sorted with the most recent episodes at the top (enqueue location: front).

When I open the news queue, sometimes I want to reorder the recent episodes for various reasons (time constraints, listening partner, mood, topic preference, etc.) I feel this is one of the basic functions of a queue: to allow the user to enqueue episodes in the order they like.

We used to be able to do this, and as far as I was concerned it worked fine. I never encountered any bugs.

**Comment by XilinJia** [comment]
Thanks for the note. It was temporarily disabled when making changes.  Will be back soon.

**Comment by XilinJia** [comment]
This is back in 6.12.6

**Comment by XilinJia** [comment]
does this work well?

**Comment by ehula** [comment]
It's not working well. I sent an email to you, but maybe you didn't get it.

> That's great, but it is not working as well as before, or like any other app does sorting. I assume you have switched libraries, but this one is not great. There is no haptic feedback when selecting an item. There is no real time shuffling of items as the selected item is moved around, resorted item sometimes get placed off the top of the screen. Is there any way to make this like it was, like other apps?

**Comment by XilinJia** [comment]
I see, thanks for the note.

For now, it's good enough that it works.  Will refine in case of serious issues or higher demand.
