### ISSUE TITLE
Sleep timer shows "Default Bin"

### ISSUE THREAD

**Issue by jonfre** [XilinJia/Podcini#103]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.11.4

### Where did you get the app from

F-Droid

### Android version

GrapheneOS

### Steps to reproduce

1. Open queue
2. Press sleep timer icon

### Expected behaviour

A sleep timer dialog

### Current behaviour

"Default Bin" page shows

**Comment by XilinJia** [comment]
The "timer" icon in Queues view opens the "Bin" of the current Queue, where locate all the episodes that have been removed from the queue.  It's not meant for the Sleeper timer. (does it make more sense to put the sleep timer here?)

To get the sleep timer, tap the icon on the PlayerUI at the bottom to expand to the player detailed view. There at the top is the sleep timer.

BTW, something related to the above might have changed from version 6.11.4.

**Comment by jonfre** [comment]
Ok sorry, I was mistaken by the clock icon. I'll close this.
Thanks

**Comment by XilinJia** [comment]
I'd like to hear any arguments on whether the sleep timer should better be at the Queues view.

**Comment by jonfre** [comment]
I think it belongs to the player.
