### ISSUE TITLE
Default page "remember last" stuck in Logs

### ISSUE THREAD

**Issue by jonfre** [XilinJia/Podcini#105]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.11.4

### Where did you get the app from

Google Play

### Android version

GrapheneOS

### Steps to reproduce

1. Set default page to "remember last"
2. Select Logs in the nav drawer
3. Log page shows without nav drawer icon.
4. No way out but to exit app

### Expected behaviour

Show nav drawer icon in Logs view

### Current behaviour

Start app and stuck in Logs view.

**Comment by XilinJia** [comment]
Thanks for the report. That's a serious issue.

A current workaround is to swipe from the left edge to open the NavDrawer.

**Comment by XilinJia** [comment]
fixed in 6.12.0
