### ISSUE TITLE
Smart home streaming button missing in "play" version.

### ISSUE THREAD

**Issue by Thunderhawk2001** [XilinJia/Podcini#106]
### Checklist

- [ ] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.12.0 (Podcini.R_release_play_6.12.0_arm64-v8a.apk)

### Where did you get the app from

Other

### Android version

Android 15

### First occurred

Version 6.11 or 6.10. no longer sure. With the current change to the design of the "full screen player".

### Steps to reproduce

1. Start playing something
2. Click on the controls on the bottom to bring up the "full screen player" view.
3. Search for "Stream" Button, to play on smart home speaker[](url)

### Expected behaviour

Find and us the stream button.

### Current behaviour

Stream button nowhere to be found.

**Comment by XilinJia** [comment]
I'm not exactly sure if I understand you correctly, but

if you want to cast to a speaker, you should install the "play" apk, not the "free" one, as I mentioned in heading of the Readme.

If you want to stream (play online media) rather than play, on the episodes lists, the action button on the right-hand side, is long-clickable. Once long clicked, a menu will pop up for your choice of other actions.

I've not used the cast function, so not sure if this gets you to the right direction.

**Comment by Thunderhawk2001** [comment]
Good morning,

Just reinstalled an older version: Podcini.R_release_play_6.10.0_arm64-v8a

And the control button is back:

![1000060120](https://github.com/user-attachments/assets/4a4535aa-0bff-438c-a0e0-6759c6e53b5b)

Might stay on this version for now.

**Comment by XilinJia** [comment]
I see.  Omitted it when transitioning to Compose.  Looking to added shortly.  Thanks for reporting.

**Comment by Thunderhawk2001** [comment]
You Sir are awesome. Thanks a lot!

And please excuse me, if I sounded aggressive. Was not my intention.

**Comment by XilinJia** [comment]
I didn't find you aggressive, probably you weren't aggressive enough ;)

Ok, just added it back in 6.12.1 to be released in a few minutes.

**Comment by Thunderhawk2001** [comment]
Just tested it. Working like a charm.
Thanks again.

Only thing still not working are the two buttons "+30sec" or "-10 sec" (default configuration) and setting the progress via the play progress bar. Wanted to make a new issue for that since a while, but totally forgot 🙈

**Comment by XilinJia** [comment]
they don't work with my test.  Did it work before?

**Comment by XilinJia** [comment]
OK, found the problem. The fix will be in the coming release.
Seems like the issue existed since very early in the project.

**Comment by Thunderhawk2001** [comment]
And again: rewind and forward are working perfectly now, only thing still not working is tapping/sliding the progress bar to select a time. 

Thank you.

**Comment by XilinJia** [comment]
> tapping/sliding the progress bar

I thought I tried it and it worked. Will try again shortly.

**Comment by XilinJia** [comment]
OK. with 6.13.0, it should work.

**Comment by Thunderhawk2001** [comment]
Yes, it's working. 
And again: Thank You.

**Comment by XilinJia** [comment]
Actually, rewind/forward/tapping are messed up a bit in 6.13.0, in both play and free versions.  Will fix shortly.
