### ISSUE TITLE
Ultima actualización no funciona 

### ISSUE THREAD

**Issue by Hildorien66** [XilinJia/Podcini#110]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.11.7

### Where did you get the app from

F-Droid

### Android version

13

### Device model

Motog20

### First occurred

Today

### Steps to reproduce

Se actualizo ayer, ya nunca fue posible ABRIRLA

### Expected behaviour

Que funcione

### Current behaviour

No se abre la app

### Logs

No se abre la app

**Comment by XilinJia** [comment]
Lo siento. ¿Puedes dar algún detalle? ¿Desde qué versión actualizaste a la 6.11.7?

Las versiones F-droid están bastante rezagadas. La versión actual es 6.12.7 en Github.  ¿Podrías intentar eso?

**Comment by XilinJia** [comment]
no longer a problem?
