### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [XilinJia/Podcini#111]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.12.8

### Where did you get the app from

F-Droid

### Android version

14

### Current behaviour

[Podcini.R_release_free_6.12.8.apk.html.zip](https://github.com/user-attachments/files/17552389/Podcini.R_release_free_6.12.8.apk.html.zip)

Is the jdk changed? Could you please take a look? Thanks!

**Comment by XilinJia** [comment]
Perhaps due to an unclean build?  Will make a new build now.

**Comment by XilinJia** [comment]
uploaded a new build. Could you try again?

**Comment by linsui** [comment]
The apk is identical to the old one.

**Comment by XilinJia** [comment]
> The apk is identical to the old one.

Sorry. I uploaded from the old directory.  Just uploaded the new one.  Please try.
