### ISSUE TITLE
Remove Dependency metadata for F-Droid

### ISSUE THREAD

**Issue by linsui** [XilinJia/Podcini#112]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.13.1

### Where did you get the app from

F-Droid

### Android version

14

### Steps to reproduce

See Frosting in APK analysis. https://beta.pithus.org/report/b70503d652720985965007605ed079d2a1996054907cf3211a2b989a43e0885f This block is encrypted with Google's public key so it can't be read by others. Could you please remove it?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by XilinJia** [comment]
where do you see that block?  I can't find it.

**Comment by linsui** [comment]
![图片](https://github.com/user-attachments/assets/51669949-5a11-4781-8e4b-b74f92701c92)

It's here. :)

**Comment by XilinJia** [comment]
Hum? not sure what that means. is the block you quoted in the signature file? do I need to change my signature file? Will investigate, or do you have some specific advice?

**Comment by linsui** [comment]
It's not in signature. See https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1. You can disable it with

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

**Comment by XilinJia** [comment]
Not fully understanding the impacts, I added that block in 6.13.2 release.

**Comment by linsui** [comment]
Thanks!
