### ISSUE TITLE
Unable to remove subscription

### ISSUE THREAD

**Issue by arias01pangolin** [XilinJia/Podcini#116]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.4.0

### Where did you get the app from

F-Droid

### Android version

9

### Device model

moto e6

### First occurred

Today

### Steps to reproduce

1. Import faulty .opml
2. Open subscription page to the first podcast listed on .opml
3. Select "Remove Podcast"

### Expected behaviour

Podcast is removed

### Current behaviour

Podcast remains in subscriptions

**Comment by arias01pangolin** [comment]
I fixed this issue with the following steps:
1. Export .opml
2. Edit the .opml with notepad, remove the offending podcast
3. Delete all Podcini data on the phone
4. Import the new .opml

**Comment by XilinJia** [comment]
Can you send the content of the faulty podcast in the opml file?

BTW, 6.4.0 is quite old, do you have a reason to continue using that?
