### ISSUE TITLE
Track search don't work well with Chinese/中文曲目搜索异常

### ISSUE THREAD

**Issue by Clayblockunova** [XilinJia/Podcini#119]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.12.8

### Where did you get the app from

Other

### Android version

HarmonyOS 3.0.0 (custom rom)

### Device model

Huawei Mate 10 Pro

### First occurred

recently

### Steps to reproduce

1,open search box in subscription or track page
2,search in Chinese
1，在订阅或曲目页面打开搜索框
2，使用中文搜索

### Expected behaviour

find related tracks (excepted to be from Chinese podcasts)
搜到相关曲目（预期均来自中文播客）

### Current behaviour

find somewhat unrelated tracks (e.g. searching "北极" would return result from Accidental Tech Podcast when subscribed, which is an English podcast)
搜到某种程度上无关的曲目（如，搜索“北极”一词时，在已收听英文播客Accidental Tech Podcast的前提下会搜索到来自该播客的节目）

**Comment by XilinJia** [comment]
Hum, will need to think about how to make it work.

Currently, the DB supports fulltext search to search on full word. So I can imagine, if you have text "搜索 北极 一词", and when you search for 北极, you should get results (you can test this by adding some text in an opinion/comment and search for a word in it). But with all the text connected together as a single word, like: "搜索北极一词", it doesn't get it.

**Comment by Clayblockunova** [comment]
Accidental Tech Podcast is the only English case which I've got, but Japanese podcast like IGN JAPAN 銀幕にポップコーン can be seen sometimes.
for Chinese, I get vol. 185 of 一言不合 when searching "北极", which doesn't contain that word in the description. the worse thing is, although "北极" is a Simplified Chinese word, searching result would return Traditional Chinese podcast like 馬力歐陪你喝一杯.
Accidental Tech Podcast是我仅有搜到过的英文播客，但是有时会搜到IGN JAPAN 銀幕にポップコーン一类的日文播客。
在中文范围内，搜索“北极”时会搜到一言不合vol. 185，其描述文本不含“北极”一词。更糟糕的情况是，尽管“北极”是简体中文，但是会搜到馬力歐陪你喝一杯一类的繁体中文播客。

**Comment by XilinJia** [comment]
I see, very interesting.  But I wasn't that lucky to get “北极” in my English collections.  Will try the podcasts you mentioned.

BTW, are you aware the search is also done on the opinions/comments you added?

**Comment by Clayblockunova** [comment]
sorry for the late reply. I‘ve never add any comment in Podcini.
抱歉，回迟了。我从未在Podcini中添加任何评论。

**Comment by XilinJia** [comment]
This appears unsolvable with the DB used:

> Character Limitations for Full-Text Search Indexes
> For Full-Text Search (FTS) indexes, only ASCII and Latin-1 alphanumerical chars (most western languages) are included in the index.
> 
> Indexes are diacritics- and case-insensitive.

**Comment by Clayblockunova** [comment]
should I open the issue in the DB's repo?
是否需要在依赖库的repo处开issue？

**Comment by XilinJia** [comment]
> should I open the issue in the DB's repo? 是否需要在依赖库的repo处开issue？

Why not? Try it here: https://github.com/realm/realm-core

**Comment by Clayblockunova** [comment]
Sorry. What is the realm version used by Podcini 6.12.8?
抱歉。请问Podcini 6.12.8对应的realm版本是？

**Comment by XilinJia** [comment]
Since long it should be the Kotlin version of 3.0.

BTW, what makes you stay with the old version of 6.12.8?  The current Podcini is 6.15.1.

**Comment by Clayblockunova** [comment]
I don't update frequently.
我不经常更新。

**Comment by XilinJia** [comment]
realm not changed

**Comment by XilinJia** [comment]
This is likely fixed in 7.1.0 as search is performed without fulltext index.  Let me know your experience.
