### ISSUE TITLE
Setting status to "played" does not set playtime to 100%

### ISSUE THREAD

**Issue by Thunderhawk2001** [XilinJia/Podcini#123]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/podcini/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/Podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

6.15.2

### Where did you get the app from

Google Play

### Problem you may be having, or feature you want

If I manually set an entry to "played" it should set the current play time to max or remove it completely, to get rid or the progression bar in the podcast list. Maybe just cosmetics, but I find it pretty strange and a bit annoying to see the green checkmark and a progress bar of about 26% or so in my nearly finished list. Doesn't feel right.

**Comment by XilinJia** [comment]
Good note.  In the code there is the option to reset position when the play state is changed. Some manual settings opt to true  and some others to false.  This needs to be better rationalized.

**Comment by XilinJia** [comment]
should be fixed in 6.15.3

**Comment by Thunderhawk2001** [comment]
Yup. Can confirm. Working now.

**Comment by Thunderhawk2001** [comment]
Yup. Can confirm. Working now.
