### ISSUE TITLE
Feature Request: All-in-one backup file

### ISSUE THREAD

**Issue by Thunderhawk2001** [XilinJia/Podcini#124]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/podcini/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/Podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

6.15.2

### Where did you get the app from

Google Play

### Problem you may be having, or feature you want

To have a complete backup I need to make 3 exports manually:
1) database 
2) preferences 
3) progress

I really like this granularity, but would be great to have a single option to create a combined/full backup: just all these 3 options combined into one file (e.g. zip).
Maybe with the option on import to select if I want to import All, or just 1,2 and/or 3.

**Comment by Thunderhawk2001** [comment]
Could even be expanded with media files. So maybe I can select what I want to have in this AiO backup file? 


Sounds like a complete overhaul of the export/import menu 🙈😅

**Comment by XilinJia** [comment]
Thanks for reporting.  I was just thinking about doing this.

**Comment by XilinJia** [comment]
in 6.15.3. Check out.

**Comment by Thunderhawk2001** [comment]
Just tried it. Works perfectly. Thank you.

**Comment by Thunderhawk2001** [comment]
Just tried it. Works perfectly. Thank you.
