### ISSUE TITLE
Reproducible Buld failed for 6.15.5

### ISSUE THREAD

**Issue by IzzySoft** [XilinJia/Podcini#129]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.15.5

### Where did you get the app from

Other

### Android version

n/a

### Steps to reproduce

1. checkout the repo (clean tree)
2. run `./gradlew assembleFreeRelease`
3. (copy signatures (we use `apksigcopier` for that)
4. compare resulting APK against the one at releases

### Expected behaviour

sha256sum hashes are identical

### Current behaviour

sha256sum hashes are NOT identical, many differences in `classes.dex`. As you do not include versionInfo with your builds, we cannot tell if your APK was really built from the commit the tag points to (as ours is), or whether this is something different.

That said: all the other releases since 6.13.7 went through the RB checks fine, this is the first one failing. I've tried with JDK-17 (which we used until the last release for Podcini), and then also with JDK-21 (as your workflows suggested you might have switched to that), seems to make no difference.

Below you find a ZIP file with the diffs:

* diff of the APK files (as signature copying failed, the certs are shown missing for our build there as well, but that can be ignored – as can the diff of the baseline, which is to be expected as the profile contains the hash of the `classes.dex`)
* diff of the `classes.dex`
* the `*.yml` containing our build recipe
* the `*.json` with the build logs

Each for JDK-17 and 21. I can also provide a diffoscope if it helps you.

### Logs

[logs.zip](https://github.com/user-attachments/files/18084673/logs.zip)

I hope the logs help you – unless you already know what might be the cause (e.g. "built from a different commit"). Would be good to have the versionInfo included, which helps in such cases :wink: 

Thanks in advance! And hope we can get at least the next releases RB again. Today's logs for Podcini are not yet published, to not mark it "failed RB" if it can be fixed with an update to our recipe, for example (an updated APK at your release won't do: the current one has already been distributed and thus should not be replaced except in "emergency cases" like security issues).

Looking forward to your reply!

**Comment by XilinJia** [comment]
Hum?

Perhaps the only difference with building 6.15.5 from previous versions is that I built an aab bundle for Google Play first, then without cleaning, built the release apks. But that could make a difference?

Anyhow, I rebuilt from the 6.15.5 source on Github and uploaded the apks.  Could you try again?

BTW, what versionInfo are you looking to see?

**Comment by IzzySoft** [comment]
> that I built an aab bundle for Google Play first, then without cleaning

Perfect explanation, matches the strange look of the diff.

> I rebuilt from the 6.15.5 source on Github and uploaded the apks

err… quoting myself from the comment before yours:

> an updated APK at your release won't do: the current one has already been distributed and thus should not be replaced except in "emergency cases" like security issues

Yes, I can try again (will do so now) – but that won't bring the shield up for this release, as the repo(s) already picked the previous APKs…

Done: RB confirmed for the new APKs. Thanks for checking, so we can a) be sure what caused it and b) avoid the mistake for future builds :wink:

> BTW, what versionInfo are you looking to see?

`META-INF/version-control-info.textproto`.It looks like this:

```yaml
repositories {
  system: GIT
  local_root_path: "$PROJECT_DIR"
  revision: "e065b1d98d15c18dff2a8d3eb8b124bb31a4e7e8"
}
```

and is controlled by the `vcsInfo.include` in the corresponding `buildType` of your `build.gradle`, and enabled by default; I see you have it [explicitly disabled](https://github.com/XilinJia/Podcini/blob/6.15.5/app/build.gradle#L140) I know [F-Droid recommends to disable it](https://f-droid.org/en/docs/Reproducible_Builds/#vcs-info) (they no longer have any RB experts and seemingly cannot deal with differences there) – but other than that page suggests, they are no stoppers for RBs but rather helpers in debugging them. I can say that as I run a verification builder and often was thankful for those hints – while able to easily "fix" when a mismatch led to non-RB.

Btw: it was never an issue with Podcini so far, so enabling it again should not endanger your F-Droid builds either. And they can always look at our recipes when in trouble, they are public ([see here](https://codeberg.org/IzzyOnDroid/rbtlog) for the builder I operate, or one of the other builders). And it's just a suggestion: thanks to your swift reply and action we were able to solve this in no time without the vcsInfo, and in this case it would just have told me to reach out to you as it would confirm both of us used the same commit…

**Comment by IzzySoft** [comment]
Just the heads-up: Today's release was RB again, thanks! And the suggestion to remove the `vcsInfo.include false` line: your decision. Given how steady your builds succeed in RB, it's nothing crucial. So feel free to close the issue :wink:

**Comment by IzzySoft** [comment]
Unfortunately, since 6.16.2 RBs fail again. Not sure if it's the same cause. Here's the diff from the 7.0.3 APKs:

```diff
  -rw-r--r--  0.0 unx    10096 b-    10096 stor 1981-01-01 01:01:02 9734baa0 lib/arm64-v8a/libandroidx.graphics.path.so
- -rw-r--r--  0.0 unx  2099504 b-  2099504 stor 1981-01-01 01:01:02 89e869d9 lib/arm64-v8a/libconscrypt_jni.so
+ -rw-r--r--  0.0 unx  2099504 b-  2099504 stor 1981-01-01 01:01:02 91d16a3c lib/arm64-v8a/libconscrypt_jni.so
  -rw-r--r--  0.0 unx 12148016 b- 12148016 stor 1981-01-01 01:01:02 818ff8e8 lib/arm64-v8a/librealmc.so
```

As that's an ELF binary, I ran diffoscope to see what the difference is:

![image](https://github.com/user-attachments/assets/53e3aa2d-ee24-4372-9a42-3fce160bbf97)

Any ideas, @XilinJia? Would be great could future releases succeed again.

**Comment by XilinJia** [comment]
Can't say for sure. F-droid reported failure recently, it was due to different versions of ndk. I had updated the ndk version on my computer, though Podcini doesn't need ndk, it's apparently affected, so as advised by f-droid, I marked the ndk version in the app's build.gragle file. Perhaps the issue with you can be resolved similarly?

**Comment by IzzySoft** [comment]
> I had updated the ndk version on my computer, though Podcini doesn't need ndk

Well, it's the `conscrypt.so` which differs, so that could very well match. I'm trying it now for 7.1.1… OK, that indeed seems to fix the issue with conscrypt. But was 7.1.1 really built from the commit the tag points to? As you've set `vcsInfo.include false` [in your build.gradle](https://github.com/XilinJia/Podcini/blob/main/app/build.gradle#L142) (could you please remove that? Other than the F-Droid documentation suggests this is no problem for RBs but rather helps debugging them should they fail), I cannot find out myself if it maybe was built from a different commit. Almost all DEX files differ:

```diff
  -rw-r--r--  0.0 unx       56 b-       52 defN 1981-01-01 01:01:02 2b084705 META-INF/com/android/build/gradle/app-metadata.properties
- -rw-r--r--  0.0 unx    10059 b-    10059 stor 1981-01-01 01:01:02 6766c55d assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx    10059 b-    10059 stor 1981-01-01 01:01:02 e013a553 assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      958 b-      958 stor 1981-01-01 01:01:02 c340e841 assets/dexopt/baseline.profm
- -rw-r--r--  0.0 unx  9788940 b-  3740667 defN 1981-01-01 01:01:02 17079684 classes.dex
+ -rw-r--r--  0.0 unx  9788940 b-  3740666 defN 1981-01-01 01:01:02 d2a23981 classes.dex
  -rw-r--r--  0.0 unx   368188 b-   164819 defN 1981-01-01 01:01:02 ea3b7cd6 classes2.dex
- -rw-r--r--  0.0 unx  8566404 b-  3547373 defN 1981-01-01 01:01:02 f8c48e64 classes3.dex
- -rw-r--r--  0.0 unx  1951612 b-   878858 defN 1981-01-01 01:01:02 4fab3362 classes4.dex
+ -rw-r--r--  0.0 unx  8566404 b-  3547373 defN 1981-01-01 01:01:02 c7386258 classes3.dex
+ -rw-r--r--  0.0 unx  1951612 b-   878859 defN 1981-01-01 01:01:02 4fd9a242 classes4.dex
  -rw-r--r--  0.0 unx    10096 b-    10096 stor 1981-01-01 01:01:02 9734baa0 lib/arm64-v8a/libandroidx.graphics.path.so
```

Though funnily only in their checksums and signatures. Did something else change? I have a gut feeling there… eh, and my gut was right: a "flaky build" (I ran it again without changing even a single character in the recipe, and it succeeded; so the build is "non-deterministic" and F-Droid just was lucky).

OK, thanks for your help again! 7.1.1 now gets the green shield up again – and should the next one fail similarly with the DEXes, I'll add our "flaky-shaker" to take care for that.
