### ISSUE TITLE
Themed icon support

### ISSUE THREAD

**Issue by matchboxbananasynergy** [XilinJia/Podcini#13]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

4.2.4

### Where did you get the app from

Other

### Problem you may be having, or feature you want

The app currently doesn't have a themed icon: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by xmha97** [comment]
+1

**Comment by o0nd7ots** [comment]
I think this should be resolved after #14.

**Comment by XilinJia** [comment]
themed icon works in 5.0.0?  Let me know.

**Comment by xmha97** [comment]
> themed icon works in 5.0.0?  Let me know.

No

![Screenshot_2024-05-12-00-51-58-520_com.miui.home.jpg](https://github.com/XilinJia/Podcini/assets/23485114/e3c5c0ba-ae62-4980-bf9e-76f24b98473a)

![Screenshot_2024-05-12-00-53-16-064_com.miui.securitycenter.jpg](https://github.com/XilinJia/Podcini/assets/23485114/c6325d6d-bf84-4458-bc03-7d2eefddd0fd)

**Comment by XilinJia** [comment]
I see.  Is that because you only had 6% of battery left ;)
