### ISSUE TITLE
No Email Client Found

### ISSUE THREAD

**Issue by toofyspooder** [XilinJia/Podcini#133]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.16.0

### Where did you get the app from

Google Play

### Android version

6.1.75-android14-11-29543898-abS928USQU4AXK 4

### Device model

Samsung S24 Ultra (SM-S928W)

### First occurred

Just Noticed Today

### Steps to reproduce

Click on the "Email to Developer" in either the Report Bug screen or About screen.

### Expected behaviour

Email client would open or a dialog from the OS would appear asking which email app to open the link in.

### Current behaviour

Displayed an error stating "You need an email client installed on the phone".
![Screenshot_20241218_055031_PodciniR](https://github.com/user-attachments/assets/d463b1b0-d0f5-4ef6-aa96-d06a4e97aa9f)

### Logs

--------- beginning of main
12-18 07:06:06.428 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleAppVisibility mAppVisible = false visible = true
12-18 07:06:06.429 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: stopped(false) old = true
12-18 07:06:06.429 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: WindowStopped on ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity set to false
12-18 07:06:06.449 22862 22862 I AppVisibilityProxy: onAppEnteredForeground
12-18 07:06:06.472 22862 22862 I BufferQueueProducer: [](id:594e00000011,api:0,p:0,c:22862) setDequeueTimeout:2077252342
12-18 07:06:06.472 22862 22862 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@bdadcb3[BugReportActivity] mNativeObject= 0xb400007ca42dcff0 sc.mNativeObject= 0xb400007b342b9510 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3085 android.view.ViewRootImpl.relayoutWindow:10224 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 android.view.Choreographer$CallbackRecord.run:1690 android.view.Choreographer$CallbackRecord.run:1699 android.view.Choreographer.doCallbacks:1154 android.view.Choreographer.doFrame:1080 android.view.Choreographer$FrameDisplayEventReceiver.run:1647 
12-18 07:06:06.472 22862 22862 I BLASTBufferQueue_Java: update, w= 1440 h= 3120 mName = ViewRootImpl@bdadcb3[BugReportActivity] mNativeObject= 0xb400007ca42dcff0 sc.mNativeObject= 0xb400007b342b9510 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3085 android.view.ViewRootImpl.relayoutWindow:10224 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 
12-18 07:06:06.473 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: Relayout returned: old=(0,0,1440,3120) new=(0,0,1440,3120) relayoutAsync=false req=(1440,3120)0 dur=5 res=0x403 s={true 0xb400007ce42f2c60} ch=true seqId=0
12-18 07:06:06.473 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0xb400007ce42f2c60} hwInitialized=true
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: QUALCOMM build                   : 11e73fe00c, I4ff0bacd4f
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Build Date                       : 03/11/24
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: E031.45.02.06
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Local Branch                     : 
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.VENDOR.14.3.0.11.00.00.973.498
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Remote Branch                    : NONE
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Build Config                     : S P 16.1.2 AArch64
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Driver Version                   : 0762.12
12-18 07:06:06.474 22862 23675 I AdrenoGLES-0: Process Name                     : ac.mdiq.podcini.R
12-18 07:06:06.474 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4781 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 android.view.Choreographer$CallbackRecord.run:1690 android.view.Choreographer$CallbackRecord.run:1699 
12-18 07:06:06.474 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: Setup new sync=wmsSync-ViewRootImpl@bdadcb3[BugReportActivity]#44
12-18 07:06:06.474 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: Creating new active sync group ViewRootImpl@bdadcb3[BugReportActivity]#45
--------- beginning of system
12-18 07:06:06.474 22862 22862 I SurfaceSyncGroup: addLocalSync=ViewRootImpl@bdadcb3[BugReportActivity]#45 to name=wmsSync-ViewRootImpl@bdadcb3[BugReportActivity]#44, callers=android.window.SurfaceSyncGroup.add:431 android.window.SurfaceSyncGroup.add:392 android.window.SurfaceSyncGroup.add:340 android.view.ViewRootImpl.createSyncIfNeeded:4912 android.view.ViewRootImpl.performTraversals:4796 android.view.ViewRootImpl.doTraversal:3345 
12-18 07:06:06.484 22862 23675 I AdrenoGLES-0: PFP: 0x01520171, ME: 0x01520023
12-18 07:06:06.486 22862 23675 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
12-18 07:06:06.496 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: registerCallbacksForSync syncBuffer=false
12-18 07:06:06.506 22862 23682 I ViewRootImpl@bdadcb3[BugReportActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
12-18 07:06:06.506 22862 23682 I ViewRootImpl@bdadcb3[BugReportActivity]: mWNT: t=0xb400007cc42a14b0 mBlastBufferQueue=0xb400007ca42dcff0 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13946 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack> 
12-18 07:06:06.506 22862 23682 I ViewRootImpl@bdadcb3[BugReportActivity]: Setting up sync and frameCommitCallback
12-18 07:06:06.513 22862 23675 I BLASTBufferQueue: [ViewRootImpl@bdadcb3[BugReportActivity]#17](f:0,a:0,s:0) onFrameAvailable the first frame is available
12-18 07:06:06.514 22862 23675 I ViewRootImpl@bdadcb3[BugReportActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
12-18 07:06:06.514 22862 23675 I SurfaceSyncGroup: onTransactionReady mName=wmsSync-ViewRootImpl@bdadcb3[BugReportActivity]#44 callback=29946420
12-18 07:06:06.514 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: reportDrawFinished seqId=0
12-18 07:06:06.517 22862 22862 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=navigationBars, host=ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity
12-18 07:06:06.517 22862 22862 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=statusBars, host=ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity
12-18 07:06:06.556 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
12-18 07:06:06.556 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007ce42f2c60}
12-18 07:06:06.558 22862 22862 D InputMethodManagerUtils: startInputInner - Id : 0
12-18 07:06:06.558 22862 22862 I InputMethodManager: startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
12-18 07:06:06.564 22862 22862 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=false, type=ime, host=ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity
12-18 07:06:06.566 22862 22873 I ViewRootImpl@bdadcb3[BugReportActivity]: Resizing android.view.ViewRootImpl@ee4f9ff: frame = [0,0][1440,3120] reportDraw = false forceLayout = false syncSeqId = -1
12-18 07:06:06.566 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1440,3120] display=[0,0][1440,3120] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false
12-18 07:06:07.474 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleWindowFocusChanged: 0 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
12-18 07:06:07.474 22862 22862 I ImeFocusController: onPreWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
12-18 07:06:07.474 22862 22862 I ImeFocusController: onPostWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
12-18 07:06:07.843 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleAppVisibility mAppVisible = true visible = false
12-18 07:06:07.845 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: destroyHardwareResources: Callers=android.view.ViewRootImpl.performTraversals:3989 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 android.view.Choreographer$CallbackRecord.run:1690 android.view.Choreographer$CallbackRecord.run:1699 android.view.Choreographer.doCallbacks:1154 android.view.Choreographer.doFrame:1080 android.view.Choreographer$FrameDisplayEventReceiver.run:1647 android.os.Handler.handleCallback:958 android.os.Handler.dispatchMessage:99 
12-18 07:06:07.846 22862 23675 D OpenGLRenderer: CacheManager::trimMemory(20)
12-18 07:06:07.853 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: Relayout returned: old=(0,0,1440,3120) new=(0,0,1440,3120) relayoutAsync=false req=(1440,3120)8 dur=4 res=0x402 s={false 0x0} ch=true seqId=0
12-18 07:06:07.854 22862 23675 D OpenGLRenderer: CacheManager::trimMemory(20)
12-18 07:06:07.863 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: stopped(true) old = false
12-18 07:06:07.863 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: WindowStopped on ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity set to true
12-18 07:06:07.864 22862 23675 D OpenGLRenderer: CacheManager::trimMemory(20)
12-18 07:06:07.866 22862 22862 I AppVisibilityProxy: onAppEnteredBackground
12-18 07:06:07.870 22862 22862 D InputTransport: Input channel destroyed: 'ClientS', fd=177
12-18 07:06:07.877 22862 22862 W GlobalMediaRouter: Ignoring invalid provider descriptor: null
12-18 07:06:17.283 22862 22862 D Choreographer: CoreRune.SYSPERF_ACTIVE_APP_BBA_ENABLE : stop animation in background states
12-18 07:06:17.283 22862 23675 D OpenGLRenderer: CacheManager::trimMemory(40)
12-18 07:06:17.284 22862 23675 D OpenGLRenderer: RenderThread::destroyRenderingContext()
12-18 07:06:17.522 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleAppVisibility mAppVisible = false visible = true
12-18 07:06:17.523 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: stopped(false) old = true
12-18 07:06:17.523 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: WindowStopped on ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity set to false
12-18 07:06:17.533 22862 22862 I BufferQueueProducer: [](id:594e00000012,api:0,p:-1,c:22862) setDequeueTimeout:2077252342
12-18 07:06:17.533 22862 22862 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@bdadcb3[BugReportActivity] mNativeObject= 0xb400007ca42dcff0 sc.mNativeObject= 0xb400007b342a1b10 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3085 android.view.ViewRootImpl.relayoutWindow:10224 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 android.view.Choreographer$CallbackRecord.run:1690 android.view.Choreographer$CallbackRecord.run:1699 android.view.Choreographer.doCallbacks:1154 android.view.Choreographer.doFrame:1080 android.view.Choreographer$FrameDisplayEventReceiver.run:1647 
12-18 07:06:17.533 22862 22862 I BLASTBufferQueue_Java: update, w= 1440 h= 3120 mName = ViewRootImpl@bdadcb3[BugReportActivity] mNativeObject= 0xb400007ca42dcff0 sc.mNativeObject= 0xb400007b342a1b10 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3085 android.view.ViewRootImpl.relayoutWindow:10224 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 
12-18 07:06:17.534 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: Relayout returned: old=(0,0,1440,3120) new=(0,0,1440,3120) relayoutAsync=false req=(1440,3120)0 dur=6 res=0x403 s={true 0xb400007ce42f2c60} ch=true seqId=0
12-18 07:06:17.534 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0xb400007ce42f2c60} hwInitialized=true
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: QUALCOMM build                   : 11e73fe00c, I4ff0bacd4f
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Build Date                       : 03/11/24
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: E031.45.02.06
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Local Branch                     : 
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.VENDOR.14.3.0.11.00.00.973.498
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Remote Branch                    : NONE
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Build Config                     : S P 16.1.2 AArch64
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Driver Version                   : 0762.12
12-18 07:06:17.534 22862 23675 I AdrenoGLES-0: Process Name                     : ac.mdiq.podcini.R
12-18 07:06:17.535 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4781 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 android.view.Choreographer$CallbackRecord.run:1690 android.view.Choreographer$CallbackRecord.run:1699 
12-18 07:06:17.535 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: Setup new sync=wmsSync-ViewRootImpl@bdadcb3[BugReportActivity]#46
12-18 07:06:17.535 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: Creating new active sync group ViewRootImpl@bdadcb3[BugReportActivity]#47
12-18 07:06:17.535 22862 22862 I SurfaceSyncGroup: addLocalSync=ViewRootImpl@bdadcb3[BugReportActivity]#47 to name=wmsSync-ViewRootImpl@bdadcb3[BugReportActivity]#46, callers=android.window.SurfaceSyncGroup.add:431 android.window.SurfaceSyncGroup.add:392 android.window.SurfaceSyncGroup.add:340 android.view.ViewRootImpl.createSyncIfNeeded:4912 android.view.ViewRootImpl.performTraversals:4796 android.view.ViewRootImpl.doTraversal:3345 
12-18 07:06:17.545 22862 23675 I AdrenoGLES-0: PFP: 0x01520171, ME: 0x01520023
12-18 07:06:17.546 22862 23675 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
12-18 07:06:17.551 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: registerCallbacksForSync syncBuffer=false
12-18 07:06:17.552 22862 23682 I ViewRootImpl@bdadcb3[BugReportActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
12-18 07:06:17.552 22862 23682 I ViewRootImpl@bdadcb3[BugReportActivity]: mWNT: t=0xb400007cc42aad50 mBlastBufferQueue=0xb400007ca42dcff0 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13946 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack> 
12-18 07:06:17.552 22862 23682 I ViewRootImpl@bdadcb3[BugReportActivity]: Setting up sync and frameCommitCallback
12-18 07:06:17.558 22862 23675 I BLASTBufferQueue: [ViewRootImpl@bdadcb3[BugReportActivity]#18](f:0,a:0,s:0) onFrameAvailable the first frame is available
12-18 07:06:17.558 22862 23675 I ViewRootImpl@bdadcb3[BugReportActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
12-18 07:06:17.558 22862 23675 I SurfaceSyncGroup: onTransactionReady mName=wmsSync-ViewRootImpl@bdadcb3[BugReportActivity]#46 callback=101966541
12-18 07:06:17.558 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: reportDrawFinished seqId=0
12-18 07:06:17.558 22862 22862 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=navigationBars, host=ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity
12-18 07:06:17.559 22862 22862 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=statusBars, host=ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity
12-18 07:06:17.577 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
12-18 07:06:17.577 22862 22862 D ViewRootImpl@bdadcb3[BugReportActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007ce42f2c60}
12-18 07:06:17.577 22862 22862 D InputMethodManagerUtils: startInputInner - Id : 0
12-18 07:06:17.577 22862 22862 I InputMethodManager: startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
12-18 07:06:17.590 22862 22862 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=false, type=ime, host=ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.BugReportActivity
12-18 07:06:17.593 22862 22873 I ViewRootImpl@bdadcb3[BugReportActivity]: Resizing android.view.ViewRootImpl@ee4f9ff: frame = [0,0][1440,3120] reportDraw = false forceLayout = false syncSeqId = -1
12-18 07:06:17.593 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1440,3120] display=[0,0][1440,3120] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false
12-18 07:06:18.217 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: ViewPostIme pointer 0
12-18 07:06:18.287 22862 22862 I ViewRootImpl@bdadcb3[BugReportActivity]: ViewPostIme pointer 1
12-18 07:06:18.308 22862 22862 I ViewRootImpl@69abc3a[PreferenceActivity]: handleAppVisibility mAppVisible = false visible = true
12-18 07:06:18.308 22862 22862 I ViewRootImpl@69abc3a[PreferenceActivity]: stopped(false) old = true
12-18 07:06:18.308 22862 22862 D ViewRootImpl@69abc3a[PreferenceActivity]: WindowStopped on ac.mdiq.podcini.R/ac.mdiq.podcini.ui.activity.PreferenceActivity set to false
12-18 07:06:18.309 22862 22862 I AppVisibilityProxy: onAppEnteredForeground
12-18 07:06:18.323 22862 22862 I BufferQueueProducer: [](id:594e00000013,api:0,p:0,c:22862) setDequeueTimeout:2077252342
12-18 07:06:18.324 22862 22862 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@69abc3a[PreferenceActivity] mNativeObject= 0xb400007ca42e0510 sc.mNativeObject= 0xb400007b342ba110 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3085 android.view.ViewRootImpl.relayoutWindow:10224 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 android.view.Choreographer$CallbackRecord.run:1690 android.view.Choreographer$CallbackRecord.run:1699 android.view.Choreographer.doCallbacks:1154 android.view.Choreographer.doFrame:1080 android.view.Choreographer$FrameDisplayEventReceiver.run:1647 
12-18 07:06:18.324 22862 22862 I BLASTBufferQueue_Java: update, w= 1440 h= 3120 mName = ViewRootImpl@69abc3a[PreferenceActivity] mNativeObject= 0xb400007ca42e0510 sc.mNativeObject= 0xb400007b342ba110 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3085 android.view.ViewRootImpl.relayoutWindow:10224 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 
12-18 07:06:18.324 22862 22862 I ViewRootImpl@69abc3a[PreferenceActivity]: Relayout returned: old=(0,0,1440,3120) new=(0,0,1440,3120) relayoutAsync=false req=(1440,3120)0 dur=6 res=0x403 s={true 0xb400007ce43219c0} ch=true seqId=0
12-18 07:06:18.324 22862 22862 D ViewRootImpl@69abc3a[PreferenceActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0xb400007ce43219c0} hwInitialized=true
12-18 07:06:18.325 22862 22862 D ViewRootImpl@69abc3a[PreferenceActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4781 android.view.ViewRootImpl.doTraversal:3345 android.view.ViewRootImpl$TraversalRunnable.run:11437 android.view.Choreographer$CallbackRecord.run:1690 android.view.Choreo

**Comment by XilinJia** [comment]
Thanks for the report.  So I was using an older way that works on older phones.
Fixed in the coming release.

**Comment by XilinJia** [comment]
This should be fixed?

**Comment by toofyspooder** [comment]
Fixed for me. The dialog to choose an email app appears as expected.
