### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [XilinJia/Podcini#134]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.16.2

### Where did you get the app from

F-Droid

### Android version

14

### Steps to reproduce

The apk is not reproducible. This is caused by ndk mismatch. Maybe you updated the ndk in your environment. Or you removed ndk. It would be better to remove all ndk installed since it's not used by podcini. Or please pin the version somewhere in the repo so that we can use the same ndk. Thanks!

**Comment by XilinJia** [comment]
Sorry about that.  I believe I updated NDK quite a while ago.  Currently it's 27.0.12077973.  I still need NDK in other projects.  How would you suggest I indicate the version in Podcini?

**Comment by linsui** [comment]
You can just write the version in a file or set that in gradle directly.

**Comment by XilinJia** [comment]
All is going well, and this can be closed?

**Comment by linsui** [comment]
Yes, thanks!
