### ISSUE TITLE
App crashes upon opening.

### ISSUE THREAD

**Issue by zoj613** [XilinJia/Podcini#135]
The app won't start anymore since the current and previous versions. I have no idea what is going on. I tried upgrading to v6.16.2 but it does not help. I don't want to uninstall because I would lose all my settings and podcast list.

**Comment by XilinJia** [comment]
Sorry about that.  Let me check.  Do you remember if you had set default page to "remember last opened"?  that might likely be the case. If so, do you remember which it was on before the crash?

BTW, in the mean time, you can re-install the previous version that doesn't have problem.  If you do, let me know which version it is.

**Comment by XilinJia** [comment]
Hum, I can't see what's wrong.  The default page customization doesn't work in the past few versions (just fixed it), so on start you are defaulted to the Subscriptions page.  Not sure why that can cause a crash.  Did you try to clear app's cache from Android settings?

**Comment by XilinJia** [comment]
Can send a screenshot?  You didn't try to install a previous version that worked?

**Comment by XilinJia** [comment]
Not sure what more can be done on this. Close, but feel free to re-open with new evidence.
