### ISSUE TITLE
Negative Play Stats

### ISSUE THREAD

**Issue by toofyspooder** [XilinJia/Podcini#137]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

7.0.0

### Where did you get the app from

Google Play

### Android version

14

### Device model

Samsung S24 Ultra (SM-S928W)

### First occurred

Unknown

### Steps to reproduce

In the "Statistics" screen there is a negative spent time. I believe spent is the total time value of episodes marked play, and duration is the amount listened to within the app?

Unsure when this happened, I believe it was working a couple weeks ago and not sure what changed.
![Screenshot_20241221_075652_PodciniR](https://github.com/user-attachments/assets/7513aafd-1415-48de-885b-df439e5ff64a)

### Expected behaviour

Value should be a positive number.

**Comment by XilinJia** [comment]
Thanks for reporting. I also noticed something strange with the time spent, will check into it.

**Comment by XilinJia** [comment]
Did you import a DB from AntennaPod, and then you see this?

**Comment by toofyspooder** [comment]
No. I did try the reworked sync and and then noticed this. I couldn't say if they were related or not though as I don't know if it was negative before the sync.

**Comment by XilinJia** [comment]
Can't say it's related to the sync.  I just noticed on my debug app.  Seems likely related to the case where some episodes are played/paused in the past days and one tries to continue playing.  Do you feel it might be possible in your case?

**Comment by toofyspooder** [comment]
I do pause and play episodes over a day or so, sometimes more depending how when I am able to listen to them. But, I stick to onw until I have completed it. I don't generally play one episode, pause it, then switch to a different one, then pause and go back to the first, etc. I tend to listen to one until it is done, how ever many day's that takes.

**Comment by XilinJia** [comment]
likely fixed in 7.1.0. Note, prior errors can not be corrected, so to get the right numbers going forward, statistics data need to be reset, sorry. 
Let me know what you find.

**Comment by toofyspooder** [comment]
Will do. Once I see it pop up in the Play Store I will let you know what I find.

If I go back and mark the episodes as played manually again, will that time be repopulated in the statistics? I can always try and see what happens if you don't know currently.

**Comment by XilinJia** [comment]
Unfortunately, Podcini is not listed on Google Play, apparently Google doesn't like the access to Youtube. You will need to get the app here or through other free stores.

When you mark an episode as played, by default, I think it's not reflected in the statistics. But there is a filter setting in statistics "Include mark as played", after you check that, your mark-as-played episode will be reflected in statistics.

**Comment by toofyspooder** [comment]
Really? That sucks, so it will probably never be listed on the Play store then. That's not cool of them.

I'll switch over to Obtainium and get the latest version.

**Comment by toofyspooder** [comment]
Same thing unfortunately.


![Screenshot_20241227_193539_PodciniR.jpg](https://github.com/user-attachments/assets/ef27b5bd-8deb-4519-b1c7-8e5cfe00f80b)

**Comment by XilinJia** [comment]
The above is from version 7.1.0? It has a short-lived coroutine which terminates before finishing resetting the statistics data.  7.1.1 fixed that.

**Comment by toofyspooder** [comment]
That's after updating to 7.1.1

**Comment by XilinJia** [comment]
> That's after updating to 7.1.1

Hum? did you reset the data from the menu?

**Comment by toofyspooder** [comment]
Sorry, I thought I remembered that it was an automatic process when the new version was installed. Ran the reset and it's all good now.
