### ISSUE TITLE
Better Icon

### ISSUE THREAD

**Issue by firefoxlover** [XilinJia/Podcini#14]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

latest

### Where did you get the app from

Other

### Problem you may be having, or feature you want

The icon is pretty strange, and could match for a sleep timer or music player, not a podcast player.

### Suggested solution

Is using the normal antennapod icon, with slight adaptions (aa the app is basically antennapod cleaned up) an option? I think that icon is perfect.

Or, possible things:
- microphone
- radio
- ear
- antenna
- dialogue

**Comment by XilinJia** [comment]
Look at it poetically.  Podcini ~= pod singer.
And it's more tuned to Puccini than Elvis;
It's more flavored with porcini than white mushroom;
Pod is like a crescent moon, or an ear.
No antenna needed here.

**Comment by IzzySoft** [comment]
As icon relates to Fastlane as well, my I throw in a remark on `full_description.txt` here, @XilinJia? If you'd throw in an empty line before each bullet-point list (currently lines 13, 19, 24) and use an asterisk (`*`) instead the graphical dot for each item, it would perfectly render as Markdown, which makes it look much better in my repo :wink: Of course I can also render it the F-Droid way (simply replacing each newline with `<br>`), but that would only look half as good – especially with lines in the bullet-point lists breaking on smaller screens…

**Comment by XilinJia** [comment]
@IzzySoft thanks for the note.  Did as you suggested.

**Comment by IzzySoft** [comment]
Thanks! Enabled that as well then and triggered a pull, so it should reflect with the next sync around 7 pm UTC. Btw: if you want to have the screenshots ordered, and not have it starting with number 10, maybe prefix the other ones with a `0` – e.g. `01_drawer.jpg`. But do that before your app is included with F-Droid.org, else they'll duplicate things (last time I checked, their cleanup process was still broken – it's broken for years and still not fixed AFAIK).

**Comment by IzzySoft** [comment]
Oof, another one:

    ! ac.mdiq.podcini/en-US/changelogs/3020130.txt has 684 chars

Limit for Fastlane changelogs is 500 chars. They will be cut off precisely at that position if longer, even mid-word.
