### ISSUE TITLE
Episode List: make click on icon AND title open the podcast

### ISSUE THREAD

**Issue by firefoxlover** [XilinJia/Podcini#15]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

4.2.4

### Where did you get the app from

Other

### Problem you may be having, or feature you want

The episode list is really weird, as it opens a typical long-press context menu when clicking normally on the podcast title.

This makes playing podcasts hard and is not single-handed friendly

### Suggested solution

replace the current long press action #16

This is needed because the current longpress activates the selection, I would propose to open that dialog instead, which would make way more sense.

Instead the select mode should be invoked by the swipe action. 

### Screenshots / Drawings / Technical details

Will add

**Comment by XilinJia** [comment]
OK, here is what I will do.
click on the title, same as click on the icon, will open the podcast/episode.
Long clock on the title will do the selection operation, whether single or multiple.

**Comment by XilinJia** [comment]
Done in 4.2.5

**Comment by firefoxlover** [comment]
great! and what happened to the previous title-click click option? That is obsolete, right?
