### ISSUE TITLE
Episode list: remove swipe actions, activate selection instead

### ISSUE THREAD

**Issue by firefoxlover** [XilinJia/Podcini#16]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

4.2.4

### Where did you get the app from

Other

### Problem you may be having, or feature you want

The swipe mode is a duplicate of the "pen" button that is displayed in the selection mode.

### Suggested solution

The swipe gesture should instead be used to select one or more podcasts in the list.

The menu to select actions and the default settings for swipe should be removed (if this pen menu is the one that is actually wanted)

This would allow #15 to work (show podcast when clicking on icon or title, swipe to select, long press to invoke menu)

Also the immediately shown menu when long pressing is confusing and should be removed, it needs to be clicked away to continue selection, and manual selection will make more sense than selecting dozens of podcasts.

**Comment by XilinJia** [comment]
explain what swipe action you mean

**Comment by XilinJia** [comment]
This is done in 4.2.5

**Comment by firefoxlover** [comment]
the action when swiping an element to the side. When doing that once, it opens a dialog "what to you want to do when swiping", and has some defaults.

**Comment by firefoxlover** [comment]
Awesome! Way better
