### ISSUE TITLE
Readme: Remove `# Version 4` section -- it should be in Changelog

### ISSUE THREAD

**Issue by o0nd7ots** [XilinJia/Podcini#18]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

irrelevant

### Where did you get the app from

Other

### Android version

irrelevant

### Expected behaviour

Info about changes is in the changelog

### Current behaviour

Main readme holds changes for version 4.0 and 4.1

**Comment by o0nd7ots** [comment]
@XilinJia could you please explain the completed thing?

I can see the `changelog.md` and I think it's good that there is a link to it in the readme.

Still the readme file is mostly the "version 4" and I do not think it's good.

It seems to me that you want to differencieate this project from AntennaPod as much as possible and I accept that, but I think that catering not only to antennapod users, but to all android users would be better.
Right now if I have never used antennapod and just came across this app I would think it's very nerdy and compilated so I would not even try it to be honest.

I think you should try changing the frontpage to tell more about the app itself and there have a *small* section about the project's origin with a link to something bigger.

What do you think about that?

**Comment by XilinJia** [comment]
@o0nd7ots thank for the note.

I agree the Readme can be further improved.

Here are my thoughts:

Having people or even expecting people (especially the new users) to read the changelog is not a good idea. First, changelog is a flow list of changes.  What people need to see on the readme is a list of current status.  changelog is only for those interested in the history.

So, on the Readme, I extracted from the changelog only the current status of Podcini.

As to better presenting to the new readers, I agree it needs to be clearer, but I'm debating on how much of the basic features inherited from AP should be presented in this project.  As it stands, you see I basically refer the readers to AP's site for those, and only new things in Podcini are presented here.

Anyhow, I appreciate any good ideas.

**Comment by o0nd7ots** [comment]
I agree that pointing new users to the changelog is a bad idea.

 > I'm debating on how much of the basic features inherited from AP should be presented in this project.

I see and imagine this is not an easy task.

I just wanted to communicate that a wall of text is likely to thow some people off.

---

I think that there are three groups of things to present:
1. Original features
2. Inherited features
3. All features.

I imagine the readme like this:
1. "This is Podcini! It's a great app for podcasts."
2. List highlighted features
3. screenshots
4. "This project was forked from antennapod and compared to it, Podcini..."
5. the test (license and changelog links)

I assume that you would want to boast about the changes. Unfortunately as of right now I see no way to do that cleanly.

**Comment by XilinJia** [comment]
I structured the features into sections.  Any comment?

**Comment by o0nd7ots** [comment]
I think it's much better this way.

I have a [PR](https://github.com/XilinJia/Podcini/pull/36) with my suggested small changes.

In my opinion the readme still has way too much in it and the main culprits are `Version 4` and `Features and Enhancements`.

However it is good enough that I will close this issue now.

If i ever find more time i'll gladly help with writing it and am open for comment requests.
Keep up the good work!
