### ISSUE TITLE
App crashes when sorting items in playback queue

### ISSUE THREAD

**Issue by stryaponoff** [XilinJia/Podcini#19]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.2.6 (de261e2)

### Where did you get the app from

F-Droid

### Android version

14

### Device model

Pixel 7

### First occurred

today

### Steps to reproduce

1. Open playback queue screen
2. Long tap on any item in queue to select it
3. Tap on the drag area of any item and try to sort the items
4. App crashes

**Comment by XilinJia** [comment]
Got it.  Fixed in the coming version.

**Comment by stryaponoff** [comment]
Yep, now it's okay
