### ISSUE TITLE
Podcast info view is messed up

### ISSUE THREAD

**Issue by firefoxlover** [XilinJia/Podcini#21]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.3.2

### Where did you get the app from

Other

### Android version

14

### First occurred

always

### Steps to reproduce

1. Play podcast
2. Open the info view
3. Try to switch between cover and expanded info

### Expected behaviour

Normally the full icon views is there, swiping up opens the detailed text.

Swiping up and down works well to swap between these modes

### Current behaviour

I guess you want to focus the detailed view, but the current implementation is a bit buggy.

As its currently done, nobody will view the fullscreen image, as its not worth the hassle. You need to swipe down all the way, and to get back to the detail view press a button. Swiping up does not work, as that action already collapses the podcast info view.

Instead I would prefer to keep the info view as it is, as its fine. Or to open it by swiping down from the detailed view, not up from the bottom of the detail view.

So 
- click to open podcast view (showing details by default)
- swipe from top to bottom to show the fullshreen icon
- swipe from bottom to top to show the details again

**Comment by XilinJia** [comment]
I also felt this weird.  Revamped the player detailed view.  swipe no longer collapses or expands the player details, it only scrolls the content in the view.  The icon on the collapsed player expands the detailed view.  The down-arrow on the top left corner collapses the player details.  
Will be included in the coming release now.
