### ISSUE TITLE
Podcini crash when adding widget - android.widget.RelativeLayout cannot be cast to android.widget.FrameLayout

### ISSUE THREAD

**Issue by metronidazole** [XilinJia/Podcini#22]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.3.2

### Where did you get the app from

Other

### Android version

14

### First occurred

Always

### Steps to reproduce

1. Go to homescreen (e.g. nova launcher)
2. Try to add any widget from Podcini

### Expected behaviour

The widget will be added to homescreen

### Current behaviour

Podcini crashes and no widget is placed

### Logs

--------- beginning of crash
03-24 12:05:04.430 11837 11837 E AndroidRuntime: FATAL EXCEPTION: main
03-24 12:05:04.430 11837 11837 E AndroidRuntime: Process: ac.mdiq.podcini, PID: 11837
03-24 12:05:04.430 11837 11837 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{ac.mdiq.podcini/ac.mdiq.podcini.ui.activity.WidgetConfigActivity}: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.FrameLayout
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3957)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4137)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2551)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:107)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.os.Looper.loopOnce(Looper.java:232)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:317)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:8532)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
03-24 12:05:04.430 11837 11837 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.FrameLayout
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at ac.mdiq.podcini.databinding.PlayerWidgetBinding.bind(SourceFile:184)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at ac.mdiq.podcini.ui.activity.WidgetConfigActivity.onCreate(SourceFile:59)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:8820)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:8798)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1524)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3939)
03-24 12:05:04.430 11837 11837 E AndroidRuntime:    ... 15 more
03-24 12:05:04.433 11837 11837 D UserPreferences: User data folder not writable or not set. Trying default.
03-24 12:05:04.438 11837 11858 W ac.mdiq.podcini: Cleared Reference was only reachable from finalizer (only reported once)

**Comment by XilinJia** [comment]
Thanks for reporting.  Fixed in the coming release.

**Comment by XilinJia** [comment]
please verify this
