### ISSUE TITLE
Missing pixels in playback controls

### ISSUE THREAD

**Issue by ls-2020** [XilinJia/Podcini#27]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.5.1(free)

### Where did you get the app from

github

### Android version

13 (LOS 20)

### Steps to reproduce

none required, this happens always

### Expected behaviour

playback-button-area should be completely visible

### Current behaviour

playback-button-area is cut-off (half of the text-descriptions below the buttons "1.00" "15" "15"  are missing)
see attached screenshot (below this area are the three main android-navigation-buttons which are not visible in the screenshot)
if i click on the podcast image which opens the details page there is no cut-off (in all other views the playback-button-area is "cut-off")

![Screenshot_20240402](https://github.com/XilinJia/Podcini/assets/98686657/a089422e-3a33-4cfa-8a2b-638e2e9985ba)

**Comment by XilinJia** [comment]
Ohm, this is pretty strange.  On my 2 phones there is no such problem.  Added a bit bottom margin to the numbers.  Let's see if it helps, in the coming release.

**Comment by ls-2020** [comment]
not fixed in 4.5.2

**Comment by ls-2020** [comment]
this did not help there is no difference between 4.5.1 and 4.5.2
i think the whole container for image, buttons and time-progress is not aligned correctly and should be moved up.
(as mentioned above only in the podcast-view everything is placed correct without cut-off)

**Comment by XilinJia** [comment]
did some further adjustments in 4.5.3.  Please test it.

**Comment by ls-2020** [comment]
in 4.5.3 something changed:
<4.5.3 the podcast-view was OK and the other views were cut-off
now the podcast-view is cut-off as well and now all views have identical cut-off and the cut-off is not as big as before, but there are still few pixels missing at the bottom (it's an improvement)

so either more space at the bottom is required  or you revert the changes and try to align the container the way you aligned the container in the podcast-view <4.5.3

**Comment by XilinJia** [comment]
"<4.5.3 the podcast-view was OK and the other views were cut-off"
what do you mean by this?  Your screenshot was with Episodes view and you saw the cutoff, but with you change the view to Podcast from Episodes, then there was no cutoff?
I don't see how that can be different.
I am making a test version with a bit larger height.  Could you try it in a while?

**Comment by XilinJia** [comment]
here you go: https://github.com/XilinJia/Podcini/releases/tag/4.5.3.test

**Comment by ls-2020** [comment]
it is way better but still not fixed!
the text is not cut-off anymore, but few pixels at the bottom of the image are missing, so height should still be a bit larger!

yes, in <4.5.3 in the details of the episode (description/shownotes + large image) there was no cut-off so the controls looked different in the normal view and in the details (i tried to describe this in the screenshot: "click on image...")

**Comment by ls-2020** [comment]
yes, i understand and it is no big issue anymore, but maybe just give it again a bit more height (the text has no margin to android-buttons)
