### ISSUE TITLE
SponsorBlock type support

### ISSUE THREAD

**Issue by Kreuger** [XilinJia/Podcini#28]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

4.5.1

### Where did you get the app from

Other

### Problem you may be having, or feature you want

Nobody likes ads in their podcasts. Im hoping it would be possible to add this feature.

### Suggested solution

Implement some way to skip ads, like SponsorBlock for Youtube. Moral thoughts aside, some of us already support podcasts through means such as merch. We shouldnt be forced into a monthly subscription for an adfree experience.  I have yet to see a podcast app implement this. Even AntennaPod had a request but they got hung up on the moral side of it.

### Screenshots / Drawings / Technical details

Similar to SB, audio progressbar would have colours to show where ads are, different for sponsored segments, etc. When skipping, a toast notification should be displayed.

**Comment by XilinJia** [comment]
Ohm, personally, I'm inclined on giving the content creators some support, especially since podcast listening is quite unlike web browsing in that we subscribe and listen to the contents we love.

But i will keep this up for debate now.

**Comment by ls-2020** [comment]
1. I don't like ads and block or skip them, if possible.
2. For me there are no moral thoughts as the content creators are getting there money anyway! I always download the complete podcast and listen to it offline, so nobody (including the sponsors) can see what part(s) i skip, so listening to ads would just waste my time and would not help the content creators in any way.

I would really like to see automated skipping of adverts, but not with SponsorBlock as it requires a web-service and many users who mark parts of each episode of a podcast as adverts, so blocking adverts would only work on very popular podcasts

Probably the easiest way would  be to contact the hosts of the podcasts and tell them that you understand that adverts are necessary and that you accept adverts at the start and end of the podcast (don't mention that you can auto-skip them) and then explain how annoying adverts in the middle of a talk are. If enough users complain it may help.

**Comment by o0nd7ots** [comment]
I think you should try to raise this idea at AntennaPod.
From what I can see it has more contributors so somebody could pick this up.
Porting it to Kotlin wouldn't be hard I suppose.

**Comment by Kreuger** [comment]
> I think you should try to raise this idea at AntennaPod. From what I can see it has more contributors so somebody could pick this up. Porting it to Kotlin wouldn't be hard I suppose.

Theyve already shot down the idea for the same reason.

**Comment by Kreuger** [comment]
@XilinJia I see that you've closed this. Is it safe to assume you will not implement it?

**Comment by XilinJia** [comment]
No, sorry. For: 1) I don't quite support the idea; 2) I don't see an easy way to do it; and 3) there isn't much interest on this since April.

**Comment by Kreuger** [comment]
Okay that's fine.

**Comment by voidplayer** [comment]
There is interest, there are plenty of threads speaking about it if you search for it, its just not very easy to implement

Theres been a few different approaches to it, like making downloading the podcast twice and making a diff to find the ads

But theres nothing to overcome your number 1 reason :)

Same thing happened with youtube apps, some disagree with adding ads skipping technologies and others dont
