### ISSUE TITLE
jump introduction and final

### ISSUE THREAD

**Issue by xunil89** [XilinJia/Podcini#29]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.6.0 (3020125)

### Where did you get the app from

F-Droid

### Android version

Crdroid a13

### Device model

Miatoll

### Steps to reproduce

the jump option does not work, in the original app antennapod works, other "bug" in my autoradio antennapod peemetteva to scroll inside its folders playlists etc. now missing complete the voice, i can sollo manage the normal pause play stop commands etc

**Comment by XilinJia** [comment]
Thanks for reporting. please explain what "jump option" you mean.  Is it regarding Android Auto?  If so, I will check about it shortly.

**Comment by xunil89** [comment]
> Thanks for reporting. please explain what "jump option" you mean. Is it regarding Android Auto? If so, I will check about it shortly.

[![TBAGPINQTMHINGV.jpg](https://i.postimg.cc/tJDvy0Rb/TBAGPINQTMHINGV.jpg)](https://postimg.cc/642fLmGb)
[![WBLYDETPKKTRHQG.jpg](https://i.postimg.cc/6qBbD6Xz/WBLYDETPKKTRHQG.jpg)](https://postimg.cc/qhZGKTgC)
As for the car radio, it’s not about android cars, I just think that antennapod "sent" the playlist and playlists instead now no.. I just don’t know how else to explain to me,  other apps do it like vlc or musicolet

**Comment by xunil89** [comment]
[![UWMCNJRCAOMQVIM.jpg](https://i.postimg.cc/hvtSZ8ZG/UWMCNJRCAOMQVIM.jpg)](https://postimg.cc/DJRk8GTV)
[![XEVLIQBBFKOBFPQ.jpg](https://i.postimg.cc/Y93rxD3V/XEVLIQBBFKOBFPQ.jpg)](https://postimg.cc/hzXRDrNb)

**Comment by xunil89** [comment]
> The "jump" issue is fixed in 4.6.1
> 
> Will check about Auto.

I got to try again now and I still have both problems,  indeed I noticed a third podcasts are not marked as heard when they are completed.  I also tried to clear the cache.   it’s a user bug?  should I try to delete the app and reinstall?

**Comment by XilinJia** [comment]
I uploaded 4.6.1 twice, the first one didn't actually solve the problem, sorry if you got that one (you likely got it from f-droid as they took the first new update  available).  The current 4.6.1 on github solves it (I think).  You can stay with the f-droid build and wait for 4.6.2.

**Comment by XilinJia** [comment]
OK, now 4.6.2 also works with Android Auto.  Try it and let me know.  Thanks

**Comment by xunil89** [comment]
> OK, now 4.6.2 also works with Android Auto. Try it and let me know. Thanks

nothing unfortunately does not work neither the jump neither the menu of the car (I don’t have android auto) I enclose also the screenshoot of the third problem,  it doesn’t appear the advanced bar and not even the check already listened 
[![RQCYOGGMEBHQGVT.jpg](https://i.postimg.cc/XYCt6RfR/RQCYOGGMEBHQGVT.jpg)](https://postimg.cc/LJmxz00D)

**Comment by XilinJia** [comment]
https://github.com/XilinJia/Podcini/assets/6257601/f78996de-7fe8-4437-81c9-26812469c069

It works for me.  How did you do it differently?
Note at the end, since Podcini updates the status every 5 seconds (tries to save some energy), so the end jump is not precisely as specified, but it does work.

**Comment by XilinJia** [comment]
For the car, if you don't have Android Auto, how to you run Podcini on the car's audio?  Did you install it directly on the cay system?

**Comment by xunil89** [comment]
I simply connected the phone via bluetooth... the auotoradio reads the playlist/ playlist as it happens for other apps... the skip does not work in any way, neither at the beginning of the song nor at the end use it in the same way I used it on antennapod..  No way to send an event log?

9 apr 2024 20:39:10 Xilin Jia ***@***.***>:

**Comment by xunil89** [comment]
great job,  after a reboot everything is working,  as far as honest streaming playback was concerned I didn’t know the initial and final jump was not possible.. 

9 apr 2024 21:22:09 Xilin Jia ***@***.***>:

**Comment by XilinJia** [comment]
I made some enhancements so the skip also works with streaming.  in the coming release.
