### ISSUE TITLE
最新版本，从正在播放的播客单集点击详情，看不到播客单集的介绍。

### ISSUE THREAD

**Issue by kimijoan** [XilinJia/Podcini#31]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.6.1

### Where did you get the app from

F-Droid

### Android version

MIUI 14.0.6

### Steps to reproduce

点击APP页面下方正在播放的播客。

### Expected behaviour

1、点击 APP 页面下方正在播放的播客。
2、会显示本集播客的播客shownote.

### Current behaviour

1、点击APP页面下方正在播放的播客。
2、会显示本集播客“本集不显示展示信息”
实际这集播客是有内容shownote的。
[1712643854574](https://github.com/XilinJia/Podcini/assets/166479799/4c024fc1-a59a-487f-bdaa-984d94fe1615)

**Comment by XilinJia** [comment]
Thanks for reporting.

I just tried the episode, and got the detailed info.
![Screenshot_20240409_065732_Podcini Debug](https://github.com/XilinJia/Podcini/assets/6257601/148d13ae-dd62-4ccb-989c-d36744a69399)

Do you get the shownote by open the episode from podcast items list view?

**Comment by kimijoan** [comment]
更新到4.6.2，清除软件数据，还是这样。
在播放列表、订阅列表进入播客单集，是有单集播客介绍的，但是点击正在播放的节目，是没有单集播客介绍的。

https://github.com/XilinJia/Podcini/assets/166479799/49aeab46-d673-49ea-9ddb-bf952caa6fb0

**Comment by XilinJia** [comment]
I see.  It has to do with streaming.  I'll check.

**Comment by XilinJia** [comment]
This should be enabled in the coming release.
