### ISSUE TITLE
当有播客正在播放时，关闭软件。再重新打开软件，就不显示正在播放的播客了。

### ISSUE THREAD

**Issue by kimijoan** [XilinJia/Podcini#32]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

4.6.2

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

不知是这样设计还是怎样？
当有播客正在播放时，关闭软件。再重新打开软件，就不显示正在播放的播客了。
Antennapad 重新打开播客后是可以显示正在播放的播客的。。

https://github.com/XilinJia/Podcini/assets/166479799/c3ec6aab-034d-42de-a154-8fc97db159be

### Suggested solution

希望像Antennapad 一样显示。
当有播客正在播放时，关闭软件。再重新打开软件，还可以显示正在播放的播客。

**Comment by XilinJia** [comment]
I see.

On my Android 14 device, when throwing out Podicini during streaming, it keeps playing, and when restarting Podcini, it comes to subscription page with the audio control still playing the current audio.

On my Android 9 device, when throwing out Podicini during streaming, audio stops, and when restarting Podcini, it comes to subscription page without audio control.

If it's local audio (downloaded), Android 9 comes back in the same way with the audio control on current audio.

Will check about streaming and default page.

**Comment by XilinJia** [comment]
The player is only restored if the previous audio was downloaded.  For streaming audio it's not supported, perhaps this will be implemented in the future.
