### ISSUE TITLE
Subscriptions list says "0 episodes" even for podcasts where there are downloaded and unplayed episodes

### ISSUE THREAD

**Issue by jm355** [XilinJia/Podcini#33]
![Screenshot_20240411-105055](https://github.com/XilinJia/Podcini/assets/4341884/73b66b13-eda3-45c3-a1d0-7dfd04d67658)
![Screenshot_20240411-105102](https://github.com/XilinJia/Podcini/assets/4341884/13342c20-8b0f-4a0d-ad27-2d4535f95fd5)

**Comment by XilinJia** [comment]
Thanks for reporting.

That number currently depends on the setting of Counter in the preference.  I planned to implemented differently later, until then.

**Comment by jm355** [comment]
Ah I see, I set the setting in settings and it works now
