### ISSUE TITLE
Auto Download not working

### ISSUE THREAD

**Issue by 48-mq** [XilinJia/Podcini#38]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.9.0

### Where did you get the app from

F-Droid

### Android version

14

### Device model

Pixel 7 Pro

### First occurred

Since I started using the app about 3 weeks ago.

### Steps to reproduce

(1) Enable "automatic download" in Settings -> Downloads -> Automatic download. Set episode cache to a high enough number (or to "Unlimited"). Check the option to download when not charging.
(2) Add a podcast subscription , then check "include in auto downloads" for that subscription.
(3) Wait for a new episode to be released.

### Expected behaviour

Podcini should automatically download new episodes of podcasts where auto-download is enabled.

### Current behaviour

No automatic downloads ever occur, regardless of the settings. Similar settings in Antennapod do create working automatic downloads.

**Comment by XilinJia** [comment]
Thanks for reporting.

So all the prior versions you used never worked on this?

**Comment by 48-mq** [comment]
Correct. At least not since 4.7.1.

**Comment by XilinJia** [comment]
Thanks.  Never checked on that.  will do shortly.

**Comment by XilinJia** [comment]
should be fixed in 4.9.4.  Try it.

**Comment by 48-mq** [comment]
Thank you so much for the quick fix. I love this app!
