### ISSUE TITLE
The last digit of seconds is occasionally not visible

### ISSUE THREAD

**Issue by VS-X** [XilinJia/Podcini#39]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.9.2 (ae82900)

### Where did you get the app from

F-Droid

### Android version

14

### Device model

Oneplus 12

### First occurred

since I started using the app 2 months ago

### Steps to reproduce

1) open any episode (e.g. Safety Third, which I am listening to right now)
2) either just play normally or skip around the podcast, at some point the last digit disappears

I think that the first time I noticed it after enabling "Show remaining time", but even with that option disabled I still encounter the disappearing digit 

### Expected behaviour

The time is displayed without the digit occasionally disappearing

### Current behaviour

The last digit of seconds disappears occasionally. E.g. `00:10:30` shows as `00:10:3`. Both left and right side times are affected. Attached is a screenshot, where the time should be ~`00:00:20`, but instead it shows `00:00:2`
![Screenshot_2024_05_02_17_35_55_40_69a1496fa6aaa038611022c8e42ed6a1](https://github.com/XilinJia/Podcini/assets/8009182/f015cc59-aaae-494b-b0a7-f9b6a4a53208)
or here, both timestamps are affected:
![Screenshot_2024_05_02_17_52_28_06_69a1496fa6aaa038611022c8e42ed6a1](https://github.com/XilinJia/Podcini/assets/8009182/a58a8e6f-11f3-4bc2-92d6-7f70d970c5bd)

**Comment by XilinJia** [comment]
Thanks for reporting.
That's a bit strange, as the length of the text is set as "wrap_content".  I don't see the digit missing on my devices (Android 14 and Android 9).  It has to do with Android implementation? 
I will keep this for more observation.

**Comment by XilinJia** [comment]
not sure what to do.  close out for now.
