### ISSUE TITLE
sync devices in the local network

### ISSUE THREAD

**Issue by XilinJia** [XilinJia/Podcini#42]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

4.11

### Where did you get the app from

Other

### Problem you may be having, or feature you want

I'm creating a feature to allow sync across devices in the same network (wifi) without requiring a separate server.  So at least the introductory functionalities will be available in 4.11.0

Any thoughts and comments?

**Comment by 48-mq** [comment]
Excellent idea! Might also be nice to allow playback from Chromecast devices?

**Comment by XilinJia** [comment]
Introductory version released
