### ISSUE TITLE
Include Settings in Database Export/Import

### ISSUE THREAD

**Issue by 48-mq** [XilinJia/Podcini#44]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

4.9.6

### Where did you get the app from

F-Droid

**Comment by XilinJia** [comment]
Thanks for the suggestion.  This is realized in the coming release.

**Comment by 48-mq** [comment]
That's great, thank you!
