### ISSUE TITLE
If subscription image cannot be processed, the subscription and its episodes will show images from other subscriptions

### ISSUE THREAD

**Issue by metronidazole** [XilinJia/Podcini#47]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

5.0.1

### Where did you get the app from

Other

### Android version

14

### First occurred

Past few days

### Steps to reproduce

1. Be subscribed to any other podcast(s)
2. Subscribe to the structuring podcast: https://structuring.com.au/podcast/

### Expected behaviour

The subscription image should show for the subscription and its episodes

### Current behaviour

The episode images and subscription image shown will be random images from other subscriptions.

If i look at the database, the image_url in the feeds table is correctly set to "https://storage.buzzsprout.com/8q7e9y8iiltxoh2d573alntzotb5?.jpg" so I'm not sure why it won't show. 

This happens in a clean profile of podcini as well, so it's not my database. It also happens on different networks (i.e. probably not a network issue). It used to work fine so I'm not sure what's going on, maybe podcini has some issue with processing the subscription image?

![podcinin_bug](https://github.com/XilinJia/Podcini/assets/41497550/259873c0-b005-4620-9184-ed9d5afca9d8)

### Logs

05-12 16:38:22.680  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:24.479  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.496  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.500  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.502  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.503  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.505  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.506  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.507  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.509  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.510  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.512  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.513  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.514  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:24.516  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:25.039  8741  8741 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:25.045  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:25.056  8741  8773 D HWUI    : endAllActiveAnimators on 0x619c097680 (RippleDrawable) with handle 0x622bda9b30
05-12 16:38:25.068  8741  8741 D VRI[MainActivity]: Not drawing due to not visible
05-12 16:38:25.648  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:25.655  8741  8741 D UserPreferences: User data folder not writable or not set. Trying default.
05-12 16:38:26.199  8741  8741 D VRI[PreferenceActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:26.209  8741  8773 D HWUI    : endAllActiveAnimators on 0x619bd68a90 (RippleDrawable) with handle 0x622bd94650
05-12 16:38:26.214  8741  8741 D VRI[PreferenceActivity]: Not drawing due to not visible
05-12 16:38:30.527  8741  8741 D VRI[PreferenceActivity]: Start draw after previous draw not visible
05-12 16:38:31.066  8741  8741 D VRI[BugReportActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:31.079  8741  8741 D VRI[BugReportActivity]: Not drawing due to not visible
05-12 16:38:31.081  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@ec03a2e
05-12 16:38:31.139  8741  8741 D PlaybackSpeedUtils: using feed speed -1.0
05-12 16:38:31.139  8741  8741 D PlaybackSpeedUtils: using feed speed -1.0
05-12 16:38:31.144  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.145  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:31.154  8741  8741 D VRI[MainActivity]: Start draw after previous draw not visible
05-12 16:38:31.171  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.172  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.172  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.172  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.172  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.173  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.173  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:31.680  8741  8741 D VRI[PreferenceActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:31.695  8741  8741 D VRI[PreferenceActivity]: Not drawing due to not visible
05-12 16:38:31.699  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@54e6740
05-12 16:38:32.300  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:32.300  8741  8741 D NavDrawerFragment: saveLastNavFragment(tag: QueueFragment)
05-12 16:38:32.301  8741  8741 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
05-12 16:38:32.301  8741  8741 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-12 16:38:32.303  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:32.304  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:32.305  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:32.305  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:32.305  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:32.305  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:32.305  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:32.312  8741  8741 D QueueFragment: fragment onCreateView
05-12 16:38:32.321  8741  8741 D QueueFragment: loadItems() called
05-12 16:38:32.322  8741  8741 D QueueFragment: onEventMainThread() called with EpisodeDownloadEvent event = [ac.mdiq.podcini.util.event.EpisodeDownloadEvent@4e780b5]
05-12 16:38:32.323  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:32.323  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:32.894  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:33.244  8741  8741 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:33.255  8741  8741 D VRI[MainActivity]: Not drawing due to not visible
05-12 16:38:33.263  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@1ded541
05-12 16:38:34.100  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.120  8741  8741 D VRI[SplashActivity]: Canceling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
05-12 16:38:34.130  8741  8741 D VRI[SplashActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:34.136  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.137  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.138  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.139  8741  8741 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:34.143  8741  8741 D NavDrawerFragment: saveLastNavFragment(tag: QueueFragment)
05-12 16:38:34.143  8741  8741 W BottomSheetBehavior: BottomSheetBehavior now supports multiple callbacks. `setBottomSheetCallback()` removes all existing callbacks, including ones set internally by library authors, which may result in unintended behavior. This may change in the future. Please use `addBottomSheetCallback()` and `removeBottomSheetCallback()` instead to set your own callbacks.
05-12 16:38:34.146  8741  8741 D QueueFragment: fragment onCreateView
05-12 16:38:34.151  8741  8741 D QueueFragment: loadItems() called
05-12 16:38:34.151  8741  8741 D QueueFragment: onEventMainThread() called with EpisodeDownloadEvent event = [ac.mdiq.podcini.util.event.EpisodeDownloadEvent@4e780b5]
05-12 16:38:34.152  8741  8741 D NavDrawerFragment: fragment onCreateView
05-12 16:38:34.160  8741  8741 D PlaybackSpeedUtils: using feed speed -1.0
05-12 16:38:34.161  8741  8741 D PlaybackSpeedUtils: using feed speed -1.0
05-12 16:38:34.163  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.171  8741  8741 D VRI[SplashActivity]: Not drawing due to not visible
05-12 16:38:34.175  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.175  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.176  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.176  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.177  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.177  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.178  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.188  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.188  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.188  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.189  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.189  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.189  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.189  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:34.191  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.195  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.197  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.200  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.202  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.205  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.207  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.210  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.212  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:34.223  8741  8741 D QueueFragment: onEventMainThread() called with EpisodeDownloadEvent event = [ac.mdiq.podcini.util.event.EpisodeDownloadEvent@513b9f9]
05-12 16:38:34.436  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@fab85e4
05-12 16:38:35.796  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.811  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.814  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.815  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.817  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.818  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.819  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.820  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.822  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.823  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.824  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.825  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.826  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:35.827  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:36.347  8741  8741 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:36.362  8741  8773 D HWUI    : endAllActiveAnimators on 0x619c0048d0 (RippleDrawable) with handle 0x622bf52210
05-12 16:38:36.367  8741  8741 D VRI[MainActivity]: Not drawing due to not visible
05-12 16:38:36.714  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:36.720  8741  8741 D UserPreferences: User data folder not writable or not set. Trying default.
05-12 16:38:37.246  8741  8741 D VRI[PreferenceActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:37.261  8741  8773 D HWUI    : endAllActiveAnimators on 0x619bfbc880 (RippleDrawable) with handle 0x622bdab540
05-12 16:38:37.268  8741  8741 D VRI[PreferenceActivity]: Not drawing due to not visible
05-12 16:38:40.222  8741  8741 D VRI[PreferenceActivity]: Start draw after previous draw not visible
05-12 16:38:40.754  8741  8741 D VRI[BugReportActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:40.762  8741  8741 D VRI[BugReportActivity]: Not drawing due to not visible
05-12 16:38:40.763  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@ad2b6bc
05-12 16:38:40.966  8741  8741 D PlaybackSpeedUtils: using feed speed -1.0
05-12 16:38:40.966  8741  8741 D PlaybackSpeedUtils: using feed speed -1.0
05-12 16:38:40.972  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:40.983  8741  8741 D VRI[MainActivity]: Start draw after previous draw not visible
05-12 16:38:41.004  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:41.005  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:41.005  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:41.005  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:41.005  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:41.006  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:41.006  8741  8741 D NavDrawerFragment: getLastNavFragment() -> QueueFragment
05-12 16:38:41.516  8741  8741 D VRI[PreferenceActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:41.531  8741  8773 D HWUI    : endAllActiveAnimators on 0x619bfc0270 (RippleDrawable) with handle 0x622bf26110
05-12 16:38:41.542  8741  8741 D VRI[PreferenceActivity]: Not drawing due to not visible
05-12 16:38:41.550  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@e7d71cf
05-12 16:38:42.149  8741  8741 D NavDrawerFragment: saveLastNavFragment(tag: SubscriptionFragment)
05-12 16:38:42.149  8741  8741 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
05-12 16:38:42.149  8741  8741 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-12 16:38:42.155  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:42.157  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:42.158  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:42.158  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:42.159  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:42.159  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:42.159  8741  8741 D NavDrawerFragment: getLastNavFragment() -> SubscriptionFragment
05-12 16:38:42.171  8741  8741 D SubscriptionFragment: fragment onCreateView
05-12 16:38:42.185  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:42.185  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:42.186  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:42.189  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:42.340  8741  8764 W System  : A resource failed to call close. 
05-12 16:38:42.347  8741  8764 W System  : A resource failed to call close. 
05-12 16:38:44.808  8741  8741 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
05-12 16:38:44.808  8741  8741 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-12 16:38:44.812  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:44.831  8741  9384 W Feed sortOrder: The specified sortOrder null is invalid.
05-12 16:38:44.845  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:44.850  8741  8741 W View    : requestLayout() improperly called by androidx.appcompat.view.menu.ActionMenuItemView{653c32b VFED..C.. ......ID 0,12-144,156 #7f0a0046 app:id/action_search} during layout: running second layout pass
05-12 16:38:44.850  8741  8741 W View    : requestLayout() improperly called by androidx.appcompat.view.menu.ActionMenuItemView{58f3034 VFED..C.. ......ID 144,12-288,156 #7f0a035f app:id/sort_items} during layout: running second layout pass
05-12 16:38:44.850  8741  8741 W View    : requestLayout() improperly called by androidx.appcompat.widget.ActionMenuView{5636388 V.E...... ......ID 936,12-1344,180} during layout: running second layout pass
05-12 16:38:45.893  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:47.777  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.793  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.797  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.798  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.800  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.801  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.803  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.804  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.806  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.807  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.808  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.810  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.811  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:47.813  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:48.342  8741  8741 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:48.350  8741  8741 D AutofillManager: view not autofillable - not passing ime action check
05-12 16:38:48.358  8741  8773 D HWUI    : endAllActiveAnimators on 0x619c0048d0 (RippleDrawable) with handle 0x622bdbea10
05-12 16:38:48.366  8741  8741 D VRI[MainActivity]: Not drawing due to not visible
05-12 16:38:50.135  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:50.140  8741  8741 D UserPreferences: User data folder not writable or not set. Trying default.
05-12 16:38:50.670  8741  8741 D VRI[PreferenceActivity]: visibilityChanged oldVisibility=true newVisibility=false
05-12 16:38:50.681  8741  8773 D HWUI    : endAllActiveAnimators on 0x619bdad0f0 (RippleDrawable) with handle 0x622bd937e0
05-12 16:38:50.686  8741  8741 D VRI[PreferenceActivity]: Not drawing due to not visible
05-12 16:38:54.170  8741  9813 D SyncService: doWork() called
05-12 16:38:54.173  8741  8796 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=b3eeeb5f-8b42-494b-8742-fd59348b541c, tags={ ac.mdiq.podcini.net.sync.SyncService } ]
05-12 16:38:54.533  8741  8741 E ac.mdiq.podcini: Invalid resource ID 0x00000000.
05-12 16:38:54.865  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@8bc8f90
05-12 16:38:54.868  8741  8773 D HWUI    : endAllActiveAnimators on 0x619bda1640 (MenuPopupWindow$MenuDropDownListView) with handle 0x622bda43a0
05-12 16:38:55.854  8741  8741 D UserPreferences: User data folder not writable or not set. Trying default.
05-12 16:38:55.862  9888  9888 W libc    : Access denied finding property "ro.debuggable"
05-12 16:38:55.856  9888  9888 W logcat  : type=1400 audit(0.0:44599): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=435 scontext=u:r:untrusted_app:s0:c136,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=ac.mdiq.podcini
05-12 16:38:55.884  8741  8741 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@a50d902
05-12 16:38:55.886  8741  8773 D HWUI    : endAllActiveAnimators on 0x619bd9b5b0 (RippleDrawable) with handle 0x622be40640

**Comment by XilinJia** [comment]
Thanks for reporting.

Not sure if I reproduced the random loading of other images, but the source of this issue is the original image lacks a header.  Added support for that.  The fixes will be in the coming release.
