### ISSUE TITLE
removing server-based sync features

### ISSUE THREAD

**Issue by XilinJia** [XilinJia/Podcini#48]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

5.4.1

### Where did you get the app from

Other

### Problem you may be having, or feature you want

In the coming releases, I plan to remove the features of syncing to Gpodder and Gpoddersync servers.  Are there any compelling reasons against doing this?

### Suggested solution

Will focus more on wifi/instant sync.

**Comment by gilcu3** [comment]
Hi @XilinJia thank you for your work with `podcini`. I use this feature quite a lot, having several clients (on android and linux) on different networks with my own gpodder server to sync. I am not sure if wifi/instant sync would be a replacement for that.

**Comment by XilinJia** [comment]
OK, I will keep them for now.
