### ISSUE TITLE
Sync with Nextcloud Gpoddersync fails

### ISSUE THREAD

**Issue by theheckwr** [XilinJia/Podcini#49]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

5.4.0 (36e1823)

### Where did you get the app from

F-Droid

### Android version

LineageOS 21-24240318-NIGHLY-pstar (Android 14)

### Steps to reproduce

1. Add Sync with Nextcloud (via gpoddersync, Nextcloud hosted on subpath (e.g. example.com/nextcloud))
2. Login

### Expected behaviour

Sync successfully

### Current behaviour

Sync fails, sometimes reports: 
![Screenshot_20240528-231209_Trebuchet](https://github.com/XilinJia/Podcini/assets/22587394/2a6ae869-5316-4422-a87b-db966e30577d)

### Logs

On the server's access log:
```
2.212.xxx.xxx - - [28/May/2024:21:15:14 +0000] "GET //nextcloud/index.php/apps/gpoddersync/subscriptions?since=0 HTTP/2.0" 404 19 "-" "-" 1168800 "-" "-" 0ms
```
⇒ That "//" at the beginning seems to be the problem ([this](https://github.com/AntennaPod/AntennaPod/issues/7083) issue of Antenna Pod seems similar)

**Comment by XilinJia** [comment]
I see.  Thanks for reporting.

So someone use the server-based sync.  I was thinking about removing the feature of sync to servers, focusing more on wifi/instant sync.  Can you give some comment on #48 ?

**Comment by XilinJia** [comment]
I stripped the first "/" and a release will be out shortly.  Since I don't have such a server set up, I would rely on any feedback to see if it works.

**Comment by XilinJia** [comment]
This glitch has been there for ages, since the older AntennaPod. Amazing it's just surfaced.

**Comment by XilinJia** [comment]
Please confirm this?

**Comment by theheckwr** [comment]
Sorry, for the late reply. I've been very busy lately and F-Droid takes some time to push out your update.
Long story short: It works!
Thanks a lot for fixing!

**Comment by XilinJia** [comment]
Glad it works.

**Comment by d3ighty** [comment]
Hello, i got the Error "404" when trying to sync with gpoddersync on nextcloud. However i cant easily provide logs. Im using the newest version. AnetennaPod sync works flawless.

**Comment by XilinJia** [comment]
Sorry about that.  I will check what might a problem there. The thing again is I don't have a test environment for that.

Can someone explain in some detail why exactly you need sync with a server like gpoddersync?

**Comment by d3ighty** [comment]
In my case because I listen to podcast on my pc via nextcloud via repod addon or kasts and on my phone via podcini. In order to always have the same subscription and played Informations, it's synced with gpoddersync

**Comment by XilinJia** [comment]
I see. Do you know in which recent version the sync works?

**Comment by d3ighty** [comment]
The latest version I used before was the latest version 5,i believe. The latest one before you updated the packageid

**Comment by XilinJia** [comment]
Do you know if it's 5.5.5, 5.5.4, ...?

**Comment by XilinJia** [comment]
Hum, I see.  I guess @theheckwr confirmed it worked with 5.5.0 (or some version earlier but later than 5.4.0). Could you do a test on 5.5.0 and 5.5.1 and let me know if my assumption that the former works and the latter doesn't is correct?

**Comment by XilinJia** [comment]
One more thing, if you will, when it fails, are you able to tell if the failing likely happened during the upload stage or the download stage?

**Comment by XilinJia** [comment]
@d3ighty I think it's more likely an issue with your connection with the server.  Are you sure you have specified the correct hostname and port number etc?  When you start using Podcini.R (i.e. version 6), you need to redo the settings.  Sure, you can import the settings from version 5, but can you verify all the settings are correct, just in cases there might be errors in the import process?

**Comment by d3ighty** [comment]
5.5.0 and 5.5.1 are working, i just tested those. However i dont import settings and did a clean install, because i only need to change a few settings and and i was sure, a lot of things changed since i last updated. Hostname etc is the same for all versions.

**Comment by XilinJia** [comment]
I see.  That's good to know.
can you possibly get a server log of things like:
`2.212.xxx.xxx - - [28/May/2024:21:15:14 +0000] "GET //nextcloud/index.php/apps/gpoddersync/subscriptions?since=0 HTTP/2.0" 404 19 "-" "-" 1168800 "-" "-" 0ms`

**Comment by XilinJia** [comment]
Also, I wonder, in Settings->Synchronization, when you enter the server address in the Login dialog and then press "Proceed to login", did it succeed?

**Comment by d3ighty** [comment]
It does succeed. I'm looking if I can provide any logs.

**Comment by XilinJia** [comment]
And, if you don't mind, can you export and send me the preference file?  it should "ac.mdiq.podcini_preferences.xml" in the exported directory.

**Comment by d3ighty** [comment]
Here you go. Ive renamed to txt file. So github supports it.
[ac.mdiq.podcini.R_preferences.txt](https://github.com/user-attachments/files/16388514/ac.mdiq.podcini.R_preferences.txt)

**Comment by d3ighty** [comment]
I just exported the preferences from 5.1.1 and imported to newest 6 version, and now the syncs seems to work. Atleast it's in my sync settings and I just imported podcasts, but the episodes status, categories or whatever wasn't synced

**Comment by XilinJia** [comment]
That's interesting. can you send me the new preference file? the previous file doesn't contain relevant info, wonder why.

to update your episodes status, you need to import the podcasts first, then import the progress.  To get a best progress file, it's better exporting it from 5.5.5.

categories and podcast settings are not available for import.

**Comment by d3ighty** [comment]
New file looks identical. Which entry are you looking for?

**Comment by XilinJia** [comment]
Sorry, it should be this file instead: gpodder.net.xml

I wonder what are the differences between the new one and the old one, especially for prefGpodnetHostname, prefHostport

**Comment by d3ighty** [comment]
Also the same entry for old and new file.

**Comment by XilinJia** [comment]
Wow, that's really strange it didn't work before.

**Comment by d3ighty** [comment]
I would say, that version 6 writes doesn't save the login or whatever. I'm glad it's working with the export workaround. Looking forward for future features

**Comment by XilinJia** [comment]
So you said gpodder.net.xml is the same before and after you import the preferences?  So before importing, it has the login etc? Can you verify that?  I would like to get this right for other users.

**Comment by d3ighty** [comment]
Podcini 6 before import: no gpodderxml at all, because of the 404 error. 
Podcini 5 export gpodderxml same as exported Podcini 6 gpodderxml after importing the Podcini 5 preferences into Podcini 6.

I hope that's what you meant

**Comment by XilinJia** [comment]
I see.  Thank you.

**Comment by Dacid99** [comment]
Hey, I have the same issue trying to sync against my nextcloud. Im using the new Podcini.R version 6.6.6 from fdroid.

The main thing I can contribute to this discussion is that it did and does work with the old podcini app version 5.5.2 from fdroid.
Maybe one could just roll the respective code back to that version as a fix?

**Comment by XilinJia** [comment]
@Dacid99 Thanks for the info.  In discussing with @d3ighty , I had the impression that gpodder.net.xml  was not saved in Podcini.R, but I'm not sure how come. He seemed to work around it by importing all the preferences (including gpodder.net.xml) from version 5 and get it work for version 6. Can you test it if it's the case? Then I will try to figure out what is happening (my difficulty on this is that I don't have such a server set up for testing).

**Comment by Dacid99** [comment]
Yes I tried it and I can fully back up what has already been found. I can export the gpodder.net.xml on the old version (5.5.2), on the new version (6.6.6) it doesnt exist. When I import the preferences from the old into the new version, the sync seems to work.

**Comment by Dacid99** [comment]
I've tried looking into the code but as far as I could tell all that changed from 5.5.2 to the first version 6 fdroid release was the location of the classes in charge of sync. Maybe something in the manifest or other metafiles causes the issue. I may do some debugging tomorrow in case I remain curious of this issue..

**Comment by XilinJia** [comment]
Appreciate your effort @Dacid99

**Comment by Dacid99** [comment]
I found the bug and am looking for the best fix. Ill send you a pull request probably by tomorrow

**Comment by toofyspooder** [comment]
I am unable to get episode played state updates from Gpoddersync. Not sure if this falls under this issue or if a new one should be opened.

When syncing with nextcloud there are no errors and the podcasts I am subscribed too are synced. But not the played state. Have confirmed they are correctly stored on the server as the are synced to other players (AntennaPod).

            ## Environment
Android version: 14
OS version: 6.1.57-android14-11-29543898-abS928USQS3AXHF
Podcini version: 6.9.1
Model: SM-S928W
Device: e3q
Product: e3qcsx
            
            No crash report recorded

**Comment by XilinJia** [comment]
Perhaps @Dacid99 is more capable of sorting this out?

**Comment by Dacid99** [comment]
Ill look into it. I dont have my test phone with me right now so it may take until the weekend for me to take action

**Comment by toofyspooder** [comment]
Hello,

Was anything further found about this? I am now using the below and all my subscriptions have disappeared including listening history. As if I just downloaded the app for the first time.

            ## Environment
Android version: 14
OS version: 6.1.57-android14-11-29543898-abS928USQS3AXI1
Podcini version: 6.13.4
Model: SM-S928W
Device: e3q
Product: e3qcsx
            
            No crash report recorded

**Comment by XilinJia** [comment]
#100

**Comment by toofyspooder** [comment]
To confirm, does this mean there is no timeline or place on the roadmap to resolve the syncing issues?

**Comment by XilinJia** [comment]
Hopefully someone can contribute on this.  @Dacid99 did something on this before, not sure if he is in a position to further sort this out.  Otherwise, it's a lower priority for me, not because it's not important, but because it takes more effort for me to set up the extra testing system.

**Comment by Dacid99** [comment]
Hey sorry for taking so long, I can reproduve this to some extent but right now i dont have the time to dive deeper into this. 
If i understand correctly, this worked on antennapod and the port to kotlin probably causes the issue?

**Comment by XilinJia** [comment]
No, not due to port to kotlin (that's long time ago). Didn't it work up until some recent time?  must be due to some change in the recent few versions.

**Comment by XilinJia** [comment]
I'd like to try resolve this. Can anyone provide a guide to easily set up the server? On Linux.

**Comment by XilinJia** [comment]
> I'd like to try resolve this. Can anyone provide a guide to easily set up the server? On Linux.

NextCloud server installed, will need to set up gPodder

**Comment by XilinJia** [comment]
> I am unable to get episode played state updates from Gpoddersync. Not sure if this falls under this issue or if a new one should be opened.
> 
> When syncing with nextcloud there are no errors and the podcasts I am subscribed too are synced. But not the played state. Have confirmed they are correctly stored on the server as the are synced to other players (AntennaPod).
> 
> ```
>         ## Environment
> ```
> 
> Android version: 14 OS version: 6.1.57-android14-11-29543898-abS928USQS3AXHF Podcini version: 6.9.1 Model: SM-S928W Device: e3q Product: e3qcsx
> 
> ```
>         No crash report recorded
> ```

The recent failure appears having to do with the fact that synthetic feeds have null downloadUrl, and when synced, the required "podcast" field was absent.  That's an easy fix, and will come in the next release shortly.

**Comment by toofyspooder** [comment]
> > I am unable to get episode played state updates from Gpoddersync. Not sure if this falls under this issue or if a new one should be opened.
> > 
> > When syncing with nextcloud there are no errors and the podcasts I am subscribed too are synced. But not the played state. Have confirmed they are correctly stored on the server as the are synced to other players (AntennaPod).
> > 
> > ```
> >         ## Environment
> > ```
> > 
> > Android version: 14 OS version: 6.1.57-android14-11-29543898-abS928USQS3AXHF Podcini version: 6.9.1 Model: SM-S928W Device: e3q Product: e3qcsx
> > 
> > ```
> >         No crash report recorded
> > ```
> 
> The recent failure appears having to do with the fact that synthetic feeds have null downloadUrl, and when synced, the required "podcast" field was absent.  That's an easy fix, and will come in the next release shortly.



This is fantastic to hear. Thank you for your dedication to submitted bug reports.

**Comment by XilinJia** [comment]
NextCloud sync appears to work fine, but let me know about your experience after trying.

The sync fix supposedly should also work for Gpodder, but I can't get the app to login to the micro Gpodder server I have (AP doesn't work either).  Something is very fishy there.  Anyone use that?

**Comment by XilinJia** [comment]
Note about the sync service, it's very crude.  For episodes only the following fields are supported:

podcast, episode, guid, action, timestamp, position, started, total

**Comment by toofyspooder** [comment]
I'll set it up and give it a try. Thanks for the work on it.

**Comment by toofyspooder** [comment]
I have, and it gave me weird results. All the podcasts had null/null episodes and did eventually populate, looked like it might have worked though. I didn't want to comment on it until I had tried to pull in what it send to NextCloud.

**Comment by XilinJia** [comment]
> All the podcasts had null/null episodes

what do you mean?

**Comment by toofyspooder** [comment]
I have had this setup with my nextcloud with no errors for a few days now and looks to be working.
