### ISSUE TITLE
Sync with Podigee Not working.

### ISSUE THREAD

**Issue by WorkstationLawyer** [XilinJia/Podcini#5]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.0.1.

### Where did you get the app from

F-Droid

### Android version

12

### Device model

REDMI NOTE 9 Pro

### First occurred

Today

### Steps to reproduce

All Podcasts Form "com.podigee." are Not working. Here is an example:         
            
   E/A Error 

Technischer Grund: 

Datei-URL:
https://audio.podigee-cdn.net/1250902-m-3266be6315b3de479fa175660520d61b.mp3?source=feed

### Expected behaviour

AntennaPod has No issues with them.

### Logs

E/A Error 
Technischer Grund: 
Datei-URL:
https://audio.podigee-cdn.net/1250902-m-3266be6315b3de479fa175660520d61b.mp3?source=feed

**Comment by XilinJia** [comment]
Guess this is not an issue now with version 4.2.4?  I tried "Power to the podcast" feed  on podigee and there appears no problem.

**Comment by WorkstationLawyer** [comment]
Thank you very much. It is working beautifully now!
