### ISSUE TITLE
Adding podcast via RSS feed seems impossible.

### ISSUE THREAD

**Issue by zoj613** [XilinJia/Podcini#55]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.6.0

### Where did you get the app from

F-Droid

### Android version

Android 13

### Device model

Zenfone 8

### First occurred

since installation

### Steps to reproduce

1. Go to menu
2. select add podcast
3. select "add podcast by RSS address"
4. Attempt to paste or type an RSS url

### Expected behaviour

I expect the pasted URL to work, but it does not get pasted as expected. Also I expect the popup keyboard to be QWERTY, not the numpad.

### Current behaviour

Its impossible to paste an RSS link or even type one because the popup keyboard is the numpad, not QWERTY as I would expect.

**Comment by XilinJia** [comment]
Thanks for reporting.
First, 4.6.0 is quite old.  Do you have a reason to use that?  Current version is 5.4.2.
That said, I'm not sure if adding RSS feature has changed or not since then.  I haven't tried in "add podcast by RSS address", will try it later.  But if you just do: "add podcast", then put the RSS address in the top search bar and hit Enter, it should work.

**Comment by zoj613** [comment]
@XilinJia I just upgraded to the latest version but the problem persists. I still cannot manually paste or type an RSS feed link using the "add podcast using rss feed". What does happen in the new version is that if I copy a link prior to selecting the "add podcast using rss feed", the link will be auto copied successfully after selecting the option. I'd also like to note that simply adding the link in the usual search bar works as expected.

**Comment by XilinJia** [comment]
OK, good to hear adding the link in the usual search bar works.
I will check about "add podcast using rss feed"

**Comment by XilinJia** [comment]
Oh, I see, it only allows you to type in numbers?

**Comment by zoj613** [comment]
> Oh, I see, it only allows you to type in numbers?

Yes, this is what happens. It won't allow you to type in the rss feed link since it only pulls up the number pad. Also if you try to manually paste the RSS link after the option has been selected, it will only paste in forward slashes and not the actually link.

**Comment by XilinJia** [comment]
OK. fixed in the coming release.

**Comment by zoj613** [comment]
I just upgraded to the latest version and it solves all the problems mentioned above. Thanks for the quick fix!
