### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by Loi83** [XilinJia/Podcini#57]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

5.5.2

### Where did you get the app from

F-Droid

### Android version

14

### Device model

Pixel 8 Pro

### First occurred

A couple days

### Expected behaviour

Dosen't work with Android Auto

**Comment by XilinJia** [comment]
Thanks for reporting.

The UI for Android Auto has been broken since a few releases back.  Will look to tackle it for Podcini 6.1.  

In the mean time, if you have it connected to the car system, and select and play an episode from the phone, does the sound come out of your car's audio?

**Comment by Loi83** [comment]
Oh okay. I'm sorry, I didn't know that. I've only been around since version 5.5.1 😅 
If I start a podcast via the app beforehand, it is output via the car audio system

**Comment by XilinJia** [comment]
OK.  Once that plays, then the buttons (play, pause, rewind, forward, and perhaps skip to next) on the car's system should also work.  Can you verify?

**Comment by Loi83** [comment]
No, there is only a black screen

**Comment by XilinJia** [comment]
You don't have hardware buttons on the car system?

**Comment by Loi83** [comment]
Sure i have, but only for vloume Up/down, Power and voice .

**Comment by XilinJia** [comment]
6.4.0 enabled the Auto UI. Let me know how it works.

**Comment by XilinJia** [comment]
appears resolved.

**Comment by gitfred773202** [comment]
Podcini doesn't show in my AA HUD even after the update to 6.5.3 directly from GitHub.  I've tried wired in and with a wireless dongle.  AA ver12.6.643244, Pixel 9, Android v14.  Looking a AA version on the phone, Podcini 6.5.3 does show there .Customize launcher does not show Podcini to add/enable/move/disable/etc.  Playback does work via app buttons, but no hard buttons to play/pause/etc.

**Comment by XilinJia** [comment]
Reopen this issue.  Thanks for informing.  Will investigate.

**Comment by XilinJia** [comment]
I test, Podcini runs fine on "desktop head unit", the screenshots are on Readme.

So this appears the issue with Podcini showing up on car display, from Google document:

> To test your app in real vehicles, it must be installed from a trusted source such as the Play Store, with one exception detailed in [Allow unknown sources](https://developer.android.com/training/cars/testing#unknown-sources).

I know "such as" indicates there are other trusted sources, but I don't know which are deemed as such.  Podcini is currently not listed yet on Google Play.  To go around it, again from Google document:

> On Android Auto, there is also a [developer option](https://developer.android.com/training/cars/testing#developer-mode) to enable running apps not installed from a trusted source. This setting only applies to [media](https://developer.android.com/training/cars/media) and [messaging](https://developer.android.com/training/cars/messaging) apps

Details here: https://developer.android.com/training/cars/testing#developer-mode

Can someone test it?

**Comment by gitfred773202** [comment]
Working! Excellent!  (Odd, but understandable, behavior by the big G)
Thanks!

**Comment by XilinJia** [comment]
the work-around info is put in AndroidAuto.md.
