### ISSUE TITLE
Tile layout for Subscriptions page

### ISSUE THREAD

**Issue by summersab** [XilinJia/Podcini#60]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

5.5.2

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

Podcini uses a list view for the Subscriptions page. It takes up a lot of unnecessary space and makes managing and navigating to podcasts difficult.

### Suggested solution

AntennaPod's default layout for the Subscriptions page is a tiled view (I don't believe it supports a list view). Personally, I prefer a tiled layout because it takes up less space and makes it a lot easier to see all podcasts. Perhaps this could be added as an option.

Additionally, perhaps there could be an option to adjust the size of the tiles. AntennaPod's default was three (3) per row, but allowing it to be increased would be nice for those with larger screens.

**Comment by XilinJia** [comment]
Thanks for the suggestion.  I understand, but would need more convincing reasons for this.
The reason I chose the list view is that as one has many subscriptions, it's hard to recognize them without easily readable titles.  With the list view this is easy.  And, if you want to easily get to some subscriptions, there is the tag switch for it.  Is it not sufficient for you?

**Comment by summersab** [comment]
I can recognize my podcasts based on the image/thumbnail provided by the feed. Almost all podcasts include a thumbnail that shows the title. I don't find it necessary to read the title based on extra lines of text next to the thumbnail.

Consider something like RadioDroid. You can toggle between list and tile view. The list view shows more details about the radio station (the title, bitrate, etc) while the tiles only show the thumbnail. The thumbnails are sufficient for me to be able to select the right station, but I can toggle it to list view if I need the extra details. I sometimes toggle list view when I am mobile so I can pick the station with the lowest bitrate and save on mobile data use, but I usually keep it in tile mode because it it more compact and the thumbnails are enough for me to differentiate between the different stations.

I think the biggest reason I would like this option is because it is more compact. On AntennaPod, all of my subscriptions fit on a single page. On Podcini, it takes roughly 1.5 pages, and I have to scroll.

**Comment by XilinJia** [comment]
This is enabled as an option in 6.0.3, which I will still set as a pre-release.
