### ISSUE TITLE
Long-press filter button to enable/disable filters

### ISSUE THREAD

**Issue by summersab** [XilinJia/Podcini#61]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

5.5.2

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

This is a copy of https://github.com/AntennaPod/AntennaPod/issues/6046

Presently, a user has to clear out all selected filters to see all episodes in a subscription. If they typically have more than one filter enabled, this requires opening up the filter menu and re-enabling those filters to go back to their standard view.

### Suggested solution

It would be nice to be able to long-press the filter button to quickly enable/disable all filters for a subscription. Manually clearing out the filters isn't a major hassle, but it would be nice to have a way to quickly toggle the filters in a way that saves multiple selections.

**Comment by XilinJia** [comment]
Thanks for the suggestion.  Sounds reasonable and easy.

**Comment by summersab** [comment]
Brilliant! Thank you!

One more suggestion for this feature. One of the responses when I suggested this to the AntennaPod devs is that this feature wouldn't be obvious. Maybe you could add text to the filter dialog that said something like:

> Long-pressing the filter button will toggle these filters on and off.

**Comment by XilinJia** [comment]
not sure about putting that text, but I tint the button to red and also disabled the button single-press after long pressed, long-press again restores normal.
