### ISSUE TITLE
Tapping the media playback notification doesn't open Podcini

### ISSUE THREAD

**Issue by summersab** [XilinJia/Podcini#63]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

5.5.2

### Where did you get the app from

F-Droid

### Android version

14 (LOS 21)

### Device model

OnePlus 7 Pro

### Steps to reproduce

1. Enable the persistent media player notification in Android settings
2. Play podcast
3. Tap the notification

### Expected behaviour

Tapping the notification should open Podcini and show the currently-playing podcast.

### Current behaviour

Nothing happens.

**Comment by XilinJia** [comment]
Currently, if Podcini is not thrown out, tapping on the notification opens whatever view that was open.  When it has been thrown out, the tap opens the default view.

> Would it make more sense to open the specific podcast item that is displayed in the notification?

This can be debated. For instance, why open the podcast item? should it be the item info view, or the player detailed view?  why not the podcast episodes list view, or even the queue?

**Comment by summersab** [comment]
Maybe make this a future enhancement to add an option in Settings for what should open when tapping the notification? There are other more pressing concerns, but this is a neat idea.

**Comment by summersab** [comment]
> Fair enough. I think if Podcini is playing something (not paused), it seems logical the notification should open the player detailed view or item.

I agree with this - it's the most logical option. However, if you wanted to provide multiple options in Settings, I would suggest:
- Open currently playing episode
- Open subscription page of currently playing episode (I would probably prefer this)
- Open Queue
- Open default page
