### ISSUE TITLE
Importing DB backup causes 6.0.3 to stop working

### ISSUE THREAD

**Issue by summersab** [XilinJia/Podcini#64]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.0.3

### Where did you get the app from

Other

### Android version

14 (Lineage OS)

### Steps to reproduce

1. Create a DB backup using 5.5.2
2. Import the backup using 6.0.3
3. Try to open 6.0.3

### Expected behaviour

The app should work.

### Current behaviour

The app goes into a crash-loop and fails to open. The only solution is to clear the app storage, but any attempt to import the DB again results in the same failure.

**Comment by XilinJia** [comment]
See [Podcini 6 migrations instroctions](https://github.com/XilinJia/Podcini/blob/main/migrationTo6.md)

**Comment by summersab** [comment]
Perfect! I missed that. Thank you! You might include a notification on the import page or show an error when trying to import a Sqlite DB to avoid corrupting the app like this.

**Comment by summersab** [comment]
Since the DB import doesn't work between versions, it would be nice if there was some way to migrate played and listened episodes to the new version. I assume that is planned once v6 is released - a user's DB will be automatically upgraded to Realm upon install, correct?

For now, if I manually import/export from 5.x to 6.x, all of the episodes I have marked as played are lost. Using "Episode progress import" doesn't solve this. (Actually, using that import function seems to hang - the import progress dialog never closes. I wonder if this is supposed to import the played episode status but isn't working properly)?

**Comment by XilinJia** [comment]
A good note on a mechanism to prevent the user from importing a wrong DB file.

When V6 is released, the migration plan is the same as it is now.  I don't intend to have any SQLite routines in the V6 and beyond.  

I tested importing the progress with some versions of the V6 pre-release, all worked fine, the played positions, marked played and favorites all get imported.  it's broken in the new version? will check.

**Comment by XilinJia** [comment]
> Actually, using that import function seems to hang - the import progress dialog never closes.
I tested with recent version, import of progress works.  The import dialog is not closed before it completes the work, and it does close when finished.  If you terminate it, the import is not complete.

**Comment by XilinJia** [comment]
in the coming 6.0.5, DB import is restricted to only .realm file, and Progress import to only .json file.
