### ISSUE TITLE
Statistics not updated when importing episode progress history in Podicini 6

### ISSUE THREAD

**Issue by metronidazole** [XilinJia/Podcini#67]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.0.4

### Where did you get the app from

F-Droid

### Android version

14

### First occurred

N/A

### Steps to reproduce

1. Follow migration guide to podcini 6 (import subscriptions, then import played history) - including exporting from last version of v5
2. Go to statistics screen of podcini 6

### Expected behaviour

All the statistics showing for the imported played history

### Current behaviour

0.0 hours is shown, and only one subscription is listed (multiple times)
![podcini 6](https://github.com/XilinJia/Podcini/assets/41497550/47063685-feeb-482e-b78e-787b60cc2705)

**Comment by XilinJia** [comment]
Thanks for reporting.  Yes, I see something strange with the statistics.

**Comment by XilinJia** [comment]
fixed in the coming 6.0.5.

**Comment by XilinJia** [comment]
after you import the progress and open statistics, you would see all still are at 0.  You need to tap filter and check "include ... marked played" (neglect the dates there, I need to sort out later), then statistics should should your imported progress.  Try it.

**Comment by XilinJia** [comment]
6.0.5 fixed that.

**Comment by XilinJia** [comment]
On one of my test phone importing json is allowed, but I see on my other phone it's not allowed.  Sorry, will fix that shortly.

6.0.5 installs over and is compatible with 6.0.4, so if you already imported the progress in 6.0.4, you don't need to re-import it again.
