### ISSUE TITLE
[Feature request] More granular control of download folder

### ISSUE THREAD

**Issue by jm355** [XilinJia/Podcini#68]
With the latest version of podcini being installed in parallel with the old version, I'm trying to find a way to copy over all my downloaded episodes so I don't have to manually re-download them. The problem is, android prevents you from copying into /storage/emulated/0/Android/data/ac.mdiq.podcini.R/files/media folder. If I could change the download folder to /storage/emulated/0/podcini (for example), then I could easily copy in the downloaded episodes

**Comment by XilinJia** [comment]
Perhaps an import feature to copy the files from your defined folder would serve better?

**Comment by XilinJia** [comment]
Actually, it quite depends on Android versions. I tried on Android 9, copying to /storage/emulated/0/Android/data/ac.mdiq.podcini.R/files/media has no problem.  On Android 14, I can't even see /storage/emulated/0/Android/data/ac.mdiq.podcini.R nor /storage/emulated/0/Android/data/ac.mdiq.podcini.
What Android do you have?

**Comment by jm355** [comment]
An import feature might work too, although I think allowing the user to select a specific storage folder is the best bet. 

i'm on android 14

**Comment by XilinJia** [comment]
allowing the user to select a specific storage folder might be problematic.

I added the feature in both releases: 5.5.4 and 6.0.10, so media files can be exported/imported.

**Comment by XilinJia** [comment]
This is not as simple as I thought. The exported file names carries a media id and are a bit convoluted that can't easily be matched to an existing episode.  I will try to sort it out a bit later. With 6.0.11 release, the import function is disabled.

**Comment by XilinJia** [comment]
OK, so this is easier than I estimated.  Now import is enabled in 6.0.12.
