### ISSUE TITLE
Disabling "Pause for interruptions" does not have an effect

### ISSUE THREAD

**Issue by PatrykMis** [XilinJia/Podcini#69]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.0.9

### Where did you get the app from

GitHub Releases

### Android version

14 QPR3, GrapheneOS

### Device model

Google Pixel 8

### First occurred

In v5.x or earlier, I haven't checked it on earlier versions than v5.

### Steps to reproduce

1. Play the podcast. By default this feature is on, so if TalkBack (screen reader) starts talking, or the user receives a notification from another app, the playback pauses until that notification sound finishes or TalkBack stops talking.
2. Go to settings and disable pause for interruptions.
3. Play any podcast. The playback sound should be quieter when another app or system starts emitting sound, but it's still pausing.

In upstream AntennaPod, this setting works as expected. In my opinion, it's something regarding migration to AndroidX Media3; I will try to check the code and Media3 docs but I'm not an expert.

### Expected behaviour

The playback sound should be quieter when another app or system starts emitting sound while this setting is disabled.

### Current behaviour

The playback is still pausing while this setting is disabled.

**Comment by PatrykMis** [comment]
update: it appears to be intentional, I wasn't able to find a code to handle this case yet, maybe it's in progress and will be added after migration-related work will be finished and migration will be fully working.

**Comment by XilinJia** [comment]
I think currently all audio focus handling relies on media3.  I may visit this for any possible workaround later, but any PR is welcome on this.

**Comment by XilinJia** [comment]
Not sure what to do on this.  Closing, but feel free to re-open with new evidence.
