### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by mrjfilippo** [XilinJia/Podcini#74]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

6.1.3

### Where did you get the app from

Other

### Problem you may be having, or feature you want

A sleep timer. I enjoy listening while going to sleep and I don't want my whole queue to play.

### Suggested solution

Being able to determine to play for how long (minutes) or to chose play until the episode is done.

**Comment by mrjfilippo** [comment]
Sorry, I don't know why I couldn't find it at first. But the feature for the sleep timer to play until the episode is done would be great to have.

**Comment by XilinJia** [comment]
The setting of the sleep timer is at the action bar of player detailed view, with the zzz icon.  So when start playing something, the bottom of the screen shows the player UI with buttons, click on the image on the left, then the player detailed view opens.

Is that not a good place to set it? Let me know your ideas.

**Comment by mrjfilippo** [comment]
To me, it would make sense for it to be with the player, at the bottom, since it relates to media playing. As opposed to general podcast things at the top. But overall it's fine, at least it's there.

What do you think about having a setting that allows to play until the episode is done, not just a timer?

**Comment by XilinJia** [comment]
If lots of people sleep with Podcini, then perhaps we need to squeeze some space in the PlayerUI for zzz, otherwise, it is too crowded there.

A setting for "finish current episode" sounds good.  Will add it in the near future.  Thanks for the suggestion.

**Comment by XilinJia** [comment]
option "finish current episode" is added in 6.2.2

**Comment by mrjfilippo** [comment]
Just saw the update. Looks great, will test it out. Thanks!
