### ISSUE TITLE
Load settings from a folder.

### ISSUE THREAD

**Issue by Kreuger** [XilinJia/Podcini#75]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

6.1.5

### Where did you get the app from

FDroid

### Problem you may be having, or feature you want

Ability to load settings from files in a folder rather than manually importing them.

### Suggested solution

An update to my phone broke the intent resolver so I cant use the file chooser for anything including importing my data from an older version which I have already deleted. Is it possible to point Podcini to my backups and have it pull the info automatically?

**Comment by XilinJia** [comment]
I guess importing settings is not that critically needed as it's not too hard to set them manually in the new app.

But anyhow, the Android file system is being made very clumsy that I don't have a good taste for it.  I'm afraid I can't quickly make the feature for you.

**Comment by Kreuger** [comment]
Well I meant more of like my subscriptions, downloaded episodes and progress.

**Comment by XilinJia** [comment]
In what fashion would you like to input the folder? Typing it in?

**Comment by Kreuger** [comment]
I suppose that would work, yeah. But a lot of apps create their own folder in the main user folder and settings get stored there. I can always move the files from my backup folder if needed. I can understand if you dont wanna go that route though.

**Comment by XilinJia** [comment]
Is this a permanent situation or are you going to fix your phone?  There is not a quick and clean way to do it in Podcini, I'm afraid.

Perhaps one suggestion, if it's suitable and you haven't tried it already, is that if you had used Podcini.R before the system issue and subscribed to some podcast (or perhaps you had imported OPML file from version 5), then at the new install of Podcini.R, you have an option to restore the OPML backups from Google.  Simply head to Add subscriptions and you will be prompted to restore that.

**Comment by Kreuger** [comment]
So far I have been unable to find a solution. I may have to bite the bullet and do a factory reset. I didnt have Podcini.R before, I had the older version. And I certainly wouldnt use a Google backup. It was worth a shot to ask. Guess we can close the issue. Thanks.
