### ISSUE TITLE
"Add to queue..." from Episodes page doesn't work

### ISSUE THREAD

**Issue by ehula** [XilinJia/Podcini#79]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.3.5

### Where did you get the app from

Other

### Android version

CalyxOS 5.9.0, Android 14

### Device model

Google Pixel 6 Pro

### First occurred

always

### Steps to reproduce

1. Switch to Episodes page.
2. Long tap on an episode.
3. Tap Edit button
4. Tap "Add to queue..."

### Expected behaviour

App should display a list of Queues for me to chose from.

(By the way, the question is written, "what did you think PodVinci would do?" PodVinci? Was that the name of the app at some point?)

### Current behaviour

Nothing happens when tapping on "Add to queue..."

**Comment by XilinJia** [comment]
Fixed in the coming 6.3.6.

PodVinci? Yes, that was briefly the name initially, then I changed it.  I can't believe it's left behind in places.  Thanks for pointing it out.

**Comment by ehula** [comment]
I've tested it. Looks like it works.
