### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [XilinJia/Podcini#80]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.3.6

### Where did you get the app from

F-Droid

### Android version

10

### Steps to reproduce

https://gitlab.com/fdroid/fdroiddata/-/jobs/7549977049

The apk is built before the change committed. Please do build the apk after commit. And maybe disable the vcs-info. See https://f-droid.org/en/docs/Reproducible_Builds/#vcs-info.

**Comment by XilinJia** [comment]
I see. I did build it before git commit, but the code stayed the same.  So probably due to the VCS-info as AGP is updated to 8.5 for this release.
I'm going to rebuild with added VCS-info setting.  Should I simply replace the release of the 6.3.6, or you would want to see a new release like 6.3.6.1?

**Comment by linsui** [comment]
Up yo you. :)

**Comment by XilinJia** [comment]
OK, I re-created the 6.3.6 release with the new clean build.
Amazing speed of the build, after gradle clean, the release build took 33 seconds.  Due to the new Gradle 8.9?  Hope that works for you.

**Comment by linsui** [comment]
Thanks!
