### ISSUE TITLE
playback errors 

### ISSUE THREAD

**Issue by atamulis** [XilinJia/Podcini#83]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

5.5.2

### Where did you get the app from

F-Droid

### Android version

11

### Device model

Nokia X100

### First occurred

3 days ago

### Steps to reproduce

1 playing podcast through aux cable
2 pull aux cable - playback stops
3 hot play - playing through phone speaker
4 reinsert aux cable - continues to play through phone speaker
5 try to stop and restart... can't stop. Kill app, swipe away notification - app keeps playing!
6 restart phone

### Expected behaviour

I expected app to play through aux cable once reinserted. I also expected playback to stop once all visible evidence of app was swiped away.

### Current behaviour

App kept playing.

**Comment by XilinJia** [comment]
Thanks for reporting.

What exactly did you mean by aux cable? Ear phone?

Version 5 is no longer maintained. Can you migrate to version 6? Latest is 6.3.7.  To migrate, it's better to first update to 5.5.4.  See the migration document on Github.

**Comment by atamulis** [comment]
Yes, ear phone cable, though in this case the cable was connected to my car stereo.

I do not know why I didn't have the latest version. I will try again with that.

**Comment by XilinJia** [comment]
If you get 5.5.2 from places like F-Droid, version 6 will not show as an update to you as it's listed a different app, because it's not compatible, hence you need some migration.  Read the document.

BTW, your 5.5.2 works with Android Auto?  There is an issue about Podcini only showing black screen on Android Auto. I'm not sure since when that happens.

**Comment by XilinJia** [comment]
6.4.0 has more work on Android Auto. Let me know if that help your case.

**Comment by XilinJia** [comment]
If you haven't got Podcini to show up on you HUD, I just created an instruction in AndroidAuto.md.  Check it out.

**Comment by XilinJia** [comment]
Not sure what to do on this. Closing, but feel free to re-open with new evidence.
