### ISSUE TITLE
Some episodes failed to refresh

### ISSUE THREAD

**Issue by zuoliswt** [XilinJia/Podcini#87]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.5.5

### Where did you get the app from

Other

### Android version

Android14

### First occurred

today

### Steps to reproduce

I have always used version 5.1 APP，I downloaded version 6.5.5 today, and then introduced OPML，Then some episodes can be refreshed, and some episodes cannot refresh，But all apps in version 5.1-5.5 can be refreshed.
The error of the episode that cannot be refreshed
:IO 错误 

技术原因: 
CLEARTEXT communication to www.ximalaya.com not permitted by network security policy 

文件 URL:
http://www.ximalaya.com/album/64689453.xml

**Comment by XilinJia** [comment]
Thanks for reporting. This should have started with 6.5.2 when I disallowed http traffic relying on https.  So apparently some http is needed.  Re-enabled it in 6.5.6. Let me know if it works.

**Comment by zuoliswt** [comment]
Hello, I have updated to the 6.5.7 version. The problem has been solved, thank you very much!
