### ISSUE TITLE
If you have a lot of subscriptions, you should be able to deactivate swipe-to-refresh.

### ISSUE THREAD

**Issue by DTente** [XilinJia/Podcini#89]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/podcini/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/Podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

6.5.9

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

My number of subscriptions is over 150.
It's easy to accidentally trigger swipe-to-refresh. Once this happens, a single subscription can no longer be updated and you have to wait a long time or the update no longer ends and gives subscription error messages.

### Suggested solution

Swipe-to-refresh should only be possible with a single subscription. This could be enabled as an opt-in in the settings.

**Comment by XilinJia** [comment]
Thanks for the suggestion.  That sounds reasonable.

Tell me, also welcome others to voice in, how would you like the subscriptions be refreshed?  It's better only based on schedule? Or other better options?

**Comment by DTente** [comment]
I always turn off the time-controlled refresh of RSS or podcast readers because it hinders rapid operation.
If swipe-to-refresh comes into play, it's similar: it shouldn't hinder operation. Unfortunately, in Podcini's case, it very much does.
It would be an improvement if only a group of subscriptions were refreshed, like a number with the same tags.

**Comment by XilinJia** [comment]
a setting to disable it is added in 6.6.0 under Settings -> Interface -> Subscriptions.  Hope that helps for now.

**Comment by XilinJia** [comment]
"swipe to refresh" in both Subscriptions and FeedEpisodes views is non-blocking in 6.6.1.  There appears no need to block the app.  Let me know if you run into any issues.

**Comment by DTente** [comment]
Thank you very much, everything is fine now, I'm getting along now!
