### ISSUE TITLE
List view single click menu popup

### ISSUE THREAD

**Issue by MosheRos** [XilinJia/Podcini#9]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.2.2 (b23764f)

### Where did you get the app from

F-Droid

### Android version

12

### Device model

OnePlus 7F

### Steps to reproduce

When viewing a list of subscriptions and clicking on a podcast it brings up a menu to add tags, rename podcast, or remove podcast. Only if clicked on the podcast icon on the left side does it open the episode list. 

### Expected behaviour

Single click should open the episode list. Long press should bring up that menu.

### Current behaviour

Single click brings up the menu

**Comment by XilinJia** [comment]
This is the new way of operation starting with 4.2.2.  Goal is to streamline clicks and not always rely on long-press for menus.  Single click on the title area pops up a menu for operation on the single item.  Long-press on the title area automatically enables multi-select mode. Clicking on the icon to open the podcast/episode is more consistent with other click operations.

**Comment by incorpusyehtee** [comment]
Damn, I stopped using antennapod. Time to fork I guess.
