### ISSUE TITLE
List of bugs

### ISSUE THREAD

**Issue by Netpilgrim** [XilinJia/Podcini#92]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.6.4

### Where did you get the app from

Other

### Android version

GrapheneOS AP2A.240905.003 (Android 14)

### Device model

Google Pixel 8

### First occurred

today (2024-09-16)

### Current behaviour

I apologize—I know this is a shitty bug report, but it’s either this or not saying anything.

I’ve only checked out the app for about half an hour and observed the following problems:

- New episodes were missing after refresh. I did the refresh at about the same time in AntennaPod and Podcini with the same subscriptions. AntennaPod showed 22 new episodes for today, Podcini 11. The podcasts with the missing episodes were present in the subscriptions list and no connection errors were shown for them.
- On the player screen the icons in the upper right (sleep timer etc.) were often missing and only reappeared after completely restarting the app.
- The sleep timer icon didn’t change when the timer was activated.
- Clicking the sleep timer icon when the timer was activated first opened the dialog for setting a new timer and only after multiple seconds (!) this changed to the dialog for a running timer.
- With one played episode the history screen (which only showed this one in the list) showed a count of 2 episodes.
- An episode that was played completely (stopped by reaching the end) was shown in all lists as partially played with the progress bar only reaching about two thirds of the way.
- More of a cosmetic problem: Player elements at the bottom are shown when no episode is being played or even queued and instead of an episode title the string “Title” is shown.

I wish you the best with this project, I appreciate the changes from AntennaPod like multiple queues. But I’ll give it some time before I’ll try it again.

**Comment by XilinJia** [comment]
Thanks @Netpilgrim.  In fact, I quite appreciate your report.  Your half an hour is wonderfully effective!

Here are some answers and questions:

> The sleep timer icon didn’t change when the timer was activated.
Podcini sets to update the sleep timer every 10 seconds (you are supposed to sleep, aren't you?)
As related, if you set a new timer, the old one is replaced, regardless if it's shown or not.

The discrepancy in history view is fixed in the coming 6.6.6. This happens with the first batch of items fetched in the recycler view. Actually in your case, the number 2 is correct and it's wrong that only one episode was shown.

I was looking to set the player UI not shown if there is no media set to be played.  Thanks for the reminder.  It's done in 6.6.6.
BTW, the player progress is updated every 5 seconds in Podcini.

Regarding completely played episode not being marked as such, I produced it in a case where an episode is played and Podcini is put to the background (or screen is off) then when finished the episode is not marked as Played though the position is reset to 0. This issue is fixed in 6.6.6.  This perhaps is not exactly as you described, so I appreciate more details from you.

I'm not sure when "on the player screen the icons in the upper right (sleep timer etc.) were often missing".  Could you give more detail?

Regarding "New episodes were missing after refresh", how did you check about new episodes in Podcini as it doesn't have a dedicated view as in AP?  Podcini marks (visually and in DB) new episodes as New when first discovered but then under certain conditions (which I don't recall at the moment) changes some to Unplayed.

**Comment by XilinJia** [comment]
Some amendment in 6.6.7 for the sleep timer and icon

**Comment by Netpilgrim** [comment]
Hi, @XilinJia.

I’m glad my observations were at least somewhat helpful.

> > The sleep timer icon didn’t change when the timer was activated.
> 
> Podcini sets to update the sleep timer every 10 seconds (you are supposed to sleep, aren't you?) As related, if you set a new timer, the old one is replaced, regardless if it's shown or not.

The functionality might be there but it’s good practice to reflect changes in the UI, especially if some non-default behavior has been activated like a running timer. In this particular case users are also likely to know the function from other apps and to be expecting the icon to change (like I was).
(BTW: Personally I like to see a running countdown in the player view, which AntennaPod doesn’t have, either.)

> The discrepancy in history view is fixed in the coming 6.6.6. This happens with the first batch of items fetched in the recycler view. Actually in your case, the number 2 is correct and it's wrong that only one episode was shown.

As I had only played a single episode, I don’t see how the number 2 would be correct.

> Regarding completely played episode not being marked as such, I produced it in a case where an episode is played and Podcini is put to the background (or screen is off) then when finished the episode is not marked as Played though the position is reset to 0. This issue is fixed in 6.6.6. This perhaps is not exactly as you described, so I appreciate more details from you.

In my case the position was not reset to 0 but was stuck somewhere in the middle. IIRC it could have been the time I stopped playing the episode before resuming it a few minutes later.

> I'm not sure when "on the player screen the icons in the upper right (sleep timer etc.) were often missing". Could you give more detail?

I closed and reopened the app several times, sometimes from its widget, and more often than not there were just no icons at all in the top right of the player screen. All other elements seemed present like the description and the control elements on the bottom. Scrolling the description up and down didn’t help to resurface the icons. Quitting (not just closing) and then reopening the app always brought the icons back.

> Regarding "New episodes were missing after refresh", how did you check about new episodes in Podcini as it doesn't have a dedicated view as in AP?

It seems to have the exact same “Episodes” view as AntennaPod that can be sorted by publishing date. The content also looked the same except that entries were missing in Podcini. This might be related to the fact that I have quite a few subscriptions; right now I’m at 168 with a total of 45,295 episodes.

**Comment by XilinJia** [comment]
>  The content also looked the same except that entries were missing in Podcini.

Hum, I can't think of reasons how new episodes can be missing after refresh as the refresh process is basically looping through all the subscriptions and do the refresh one after another.  I have been using Podcini on two phones with different set of subscriptions, one with about 90 and the other 60, and haven't noticed any missing episodes, but I will pay more attention to verify.

Note, in the preferences of every subscription, there is a setting "Keep updated", which should be set to true by default (and I can't imagine you went to set any to false), if set false, the subscription is skipped during refresh.

**Comment by XilinJia** [comment]
> (BTW: Personally I like to see a running countdown in the player view, which AntennaPod doesn’t have, either.)

Explain what running countdown you would like to see.

**Comment by Netpilgrim** [comment]
> Explain what running countdown you would like to see.

This isn’t a priority by any stretch, I was just mentioning it as I was on the subject of the timer UI. When looking at the player screen while a sleep timer is active I like to see how much time is left; e.g. the Audible app has this countdown prominently displayed in the middle of the screen.

**Comment by XilinJia** [comment]
That's an interesting intention. You use the sleep timer not for sleep?

**Comment by Netpilgrim** [comment]
> That's an interesting intention. You use the sleep timer not for sleep?

Mostly I do. But I have a hard time falling asleep, so I keep extending the countdown quite often.

**Comment by XilinJia** [comment]
I see.  Adding an overlay countdown display can be quite straightforward and sounds reasonable. Will put that in a bit later.

**Comment by XilinJia** [comment]
"the icons in the upper right (sleep timer etc.) were often missing"

This was re-produced, now sure what exactly was happening with the xml menu and bottomsheet, but is re-done with Jetpack Compose. Should be fixed, in version 6.11.3.

Any other issues you notice?

**Comment by XilinJia** [comment]
close for now.  feel free to reopen with updates

**Comment by Netpilgrim** [comment]
> close for now. feel free to reopen with updates

Thanks. I’ve kept an eye on your release notes; you seem to be working a lot on this project, which makes me hope that I can switch from AntennaPod soon (really missing those multiple queues). I’ll check it out again this weekend when I have some time.
