### ISSUE TITLE
Can't Open in Huawei Mate 10 Pro / 华为Mate 10 Pro无法启动

### ISSUE THREAD

**Issue by Clayblockunova** [XilinJia/Podcini#97]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.8.6

### Where did you get the app from

Other

### Android version

HarmonyOS 3.0.0 (custom rom)

### Device model

Huawei Mate 10 Pro

### First occurred

recently

### Steps to reproduce

Just launch the app.
启动APP。

### Expected behaviour

The app should open normally.
APP 应当正常启动。

### Current behaviour

The app stays at the logo screen for about 1 minute, and return to the desktop.
APP在logo画面停留约1分钟后退回桌面。

**Comment by XilinJia** [comment]
Hum, did you try deleting it and re-install?

**Comment by Clayblockunova** [comment]
Just re-installed Podcini and Neo Store, fixed.
重装Podcini和Neo Store后问题解决。

**Comment by XilinJia** [comment]
Thanks for the info. But I wonder how come it's needed to re-install.  Did New Store mess things up?

**Comment by Clayblockunova** [comment]
When trying to update Podcini, Neo Store is going to install 2 different versions.
Neo Store在Podcini升级时企图同时安装两个不同版本。
