### ISSUE TITLE
add podcast button is always green

### ISSUE THREAD

**Issue by in-out** [XilinJia/Podcini#98]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.9.1

### Where did you get the app from

F-Droid

### Android version

oneui 5.1 android 13

### Device model

samsung s20fe

### Steps to reproduce

refresh install

### Expected behaviour

follow theme

### Current behaviour

always green ,although toggle loght/darktheme
![Screenshot_20241008_091630_PodciniR](https://github.com/user-attachments/assets/6b72acd2-5305-4759-9ceb-42772fe68753)
![Screenshot_20241008_091701_PodciniR](https://github.com/user-attachments/assets/d206693a-eb45-409c-b589-f7d70750ee4e)

**Comment by XilinJia** [comment]
Thanks for the note. Yes, agreed.  I'm not quite sure yet what to make of it.

**Comment by XilinJia** [comment]
Adjusted. I know there are more UI items that can be enhanced. Any suggestions are welcome.
