### ISSUE TITLE
Multiple Bugs, Queue, Downloads, Play Protect Warning

### ISSUE THREAD

**Issue by MrCuneiform** [XilinJia/Podcini#99]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.9.2

### Where did you get the app from

Other

### Android version

14

### Device model

Google Pixel 8 Pro

### First occurred

Since I first upgraded to version 6 about two days ago

### Steps to reproduce

Cannot associate Podcast to a queue:
1. Go to podcast settings
2. Click associate queue
3. Click custom

Cannot Delete Podcasts that failed to download:
1. Go to downloads
2. 2 select podcasts to delete

Play Protect warning:
1. Try to download from F-droid repository, either main or izzy
2.  Play Protect gives warning about app being designed for an older version of android and it being a potential security vulnerability 

### Expected behaviour

Cannot associate Podcast to a queue:
When I click custom I should be able to select a specific queue

Cannot Delete Podcasts that failed to download:
Podcast should be able to remove podcast from downloads

Play Protect warning:

### Current behaviour

**Cannot associate Podcast to a queue:**

- Custom only gives 1 option which appears to only be the active queue.

**Cannot Delete Podcasts that failed to download:**

- Complains about file not being found and that rebooting may fix it. Rebooting does not fix the problem and the podcasts can no longer be played. Clearing the storage in App Info did fix the issue.

**Play Protect warning:**

- I hypothesize this is related to the app being built for android 11. Did not see any issues about it so I though I would let you know.

**Comment by XilinJia** [comment]
Thanks for reporting.

custom queue issue is fixed in the coming release.  Sorry, introduced in 6.8.3 caused by migrating from Material Material3.

in Downloads, if some items failed to download and show up somehow in Downloads, you can't delete them since there is no media file to delete.  What to do is in the menu, there is Reconcile, select that and the DB will be re-synced with the media files existing.

Regarding the older version complaint, since 6.8.5, Podcini is built to target Android 11 to counter a long time Google issue, see issue #88 . I will change that when I find a better solution.

**Comment by MrCuneiform** [comment]
> custom queue issue is fixed in the coming release. Sorry, introduced in 6.8.3 caused by migrating from Material to Material3.
>
Alright, I shall await that release. 

> in Downloads, if some items failed to download and show up somehow in Downloads, you can't delete them since there is no media file to delete. What to do is in the menu, there is Reconcile, select that and the DB will be re-synced with the media files existing. Or, the delete button can be long-clicked, then on the popup menu, you can select download.
> 

I tried reconcile before but the program just ended up crashing. I have a backup so I'll try re downloading them so I can keep my progress history. 

> Regarding the older version complaint, since 6.8.5, Podcini is built to target Android 11 to counter a long time Google issue, see issue #88 . I will change that when I find a better solution.
>
Aye I figured that was the reason. I saw the issue but I didn't see anyone mention Play Protect getting triggered by it, so I thought I should mention it.

**Comment by XilinJia** [comment]
> reconcile before but the program just ended up crashing

Crashed?  Could you send a bug report?  From Settings -> Report bug

**Comment by XilinJia** [comment]
the custom queue fix is in 6.9.3

**Comment by MrCuneiform** [comment]
> > reconcile before but the program just ended up crashing
> 
> Crashed? Could you send a bug report? From Settings -> Report bug


## StackTrace
```
java.lang.NullPointerException
	at ac.mdiq.podcini.ui.fragment.DownloadsFragment$reconcile$1.invokeSuspend$lambda$0(DownloadsFragment.kt:179)
	at ac.mdiq.podcini.ui.fragment.DownloadsFragment$reconcile$1.$r8$lambda$LyQ_6lJk-sJiVpSbObCwTGp-d_0(DownloadsFragment.kt:0)
	at ac.mdiq.podcini.ui.fragment.DownloadsFragment$reconcile$1$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
	at ac.mdiq.podcini.storage.database.RealmDB.upsert$lambda$7(RealmDB.kt:91)
	at ac.mdiq.podcini.storage.database.RealmDB.$r8$lambda$oD8UYz8mtCG62Wq7_FZ8PJ5qZF8(RealmDB.kt:0)
	at ac.mdiq.podcini.storage.database.RealmDB$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
	at io.realm.kotlin.internal.SuspendableWriter$write$2.invokeSuspend(SuspendableWriter.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e01c1a3, Dispatchers.IO]
```

**Comment by XilinJia** [comment]
I see.  The code assumes the media of the episode is not null.  I wonder what happened before then.  Did you somehow have some media with downloadUrl being null or empty?  OK, I'm not sure if you can answer that, but could you describe what you did up to this point (or up to the point where you have some failed downloads)?  I assume you just installed Podcini.R afresh and imported some files.

**Comment by MrCuneiform** [comment]
> I see. The code assumes the media of the episode is not null. I wonder what happened before then. Did you somehow have some media with downloadUrl being null or empty? OK, I'm not sure if you can answer that, but could you describe what you did up to this point (or up to the point where you have some failed downloads)? I assume you just installed Podcini.R afresh and imported some files.

Yes, however while I imported some files I did not have any podcasts that were previously downloaded. I did not try to download podcasts until a day or so after migrating. It appears to be server side since when I look at the details I am getting a 503 error.

**Comment by XilinJia** [comment]
If you migrate from version 5 to version 6, you can export/import the downloaded media files. 6.10.0 took off the non-null assumption in Reconcile.

**Comment by MrCuneiform** [comment]
> If you migrate from version 5 to version 6, you can export/import the downloaded media files. 6.10.0 took off the non-null assumption in Reconcile.

Tested and this does work.
